### ISSUE TITLE
communicate on "compatible" nixpkgs commit id

### ISSUE THREAD

**Issue by rapenne-s** [Jovian-Experiments/Jovian-NixOS#100]
Hi, sometimes I find it hard to figure which commit one should use to build Jovian-NixOS (mostly because of mesa moving fast)

I found the file https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/nixpkgs.nix in the project, but it's not updated regularly. I don't know how this could be improved though.

In addition, this would be pretty cool if people sending PR could tell which nixpkgs commit they used to build. Maybe a simple PR template asking for the nixpkgs commit used could be a simple fix.

**Comment by samueldr** [comment]
Yes.

That pin file is not often enough updated, and really mainly was useful at the start when building an iso was required to get started. It served to communicate "latest time we (I) checked that all the things built".

While we don't have anything better to communicate it at the time (a note should be added in the README) the fair assumption is *latest `nixos-unstable`*, and that the older the `stable` fork moment is, the less likely it is to work.

Also relevant: it would be considered a bug/regression if at any point `nixos-unstable` stops working.

**Comment by samueldr** [comment]
This is now partially "fixed" with the following change:

 - https://github.com/Jovian-Experiments/Jovian-NixOS/commit/1e2eea58581e76aa1e6754a94fdbe05a6bc37a64

I'll open a fresh issue about making a PR/issue template.
