### ISSUE TITLE
Differences with main @ 20240104.1000

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#118]
Since we have the tooling, now, let's try to strive to be as close as possible for #1.

I am only comparing vendor packages, ignoring stock Arch Linux ones.

With data from:

  - https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/manifest/main

 * * *

### Unknowns

These still need to be investigated and changes triaged.

- [jupiter-main/steamos-devkit-service-0.20220401.0-7](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steamos-devkit-service-0.20220401.0-7) - Can we run this? Should we run this?
- [jupiter-main/xorg-xwayland-jupiter-jupiter.20220831.d4d883ad5-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/xorg-xwayland-jupiter-jupiter.20220831.d4d883ad5-1) - packaging changes not interesting, need to diff source with upstream

### Key SteamOS bits

These should always be packaged and at least somewhat up to date.

- [holo-main/steamos-customizations-git-20231122.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-customizations-git-20231122.1-1) - Up to date
- [jupiter-main/galileo-mura-v0.3-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/galileo-mura-v0.3-1) - OLED calibration stuff for the OLED model, included here as a dependency of gamescope-session
- [jupiter-main/gamescope-3.13.19-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/gamescope-3.13.19-2) - #261
- [jupiter-main/jupiter-dock-updater-bin-20231121.01-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-dock-updater-bin-20231121.01-1) - #261
- [jupiter-main/jupiter-fan-control-20231229.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-fan-control-20231229.1-1) - #261
- [jupiter-main/jupiter-hw-support-20240103.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-hw-support-20240103.1-1) - intentionally held back, latest tag is from wrong branch
- [jupiter-main/linux-firmware-neptune-jupiter.20231113.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/linux-firmware-neptune-jupiter.20231113.1-1) - Up to date
- [jupiter-main/linux-neptune-61-6.1.52.valve14-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/linux-neptune-61-6.1.52.valve14-1) - #261
- [jupiter-main/mangohud-0.7.0.r78.gc5c82db-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/mangohud-0.7.0.r78.gc5c82db-1) - Up to date
- [jupiter-main/mesa-radv-23.3.0_devel.177466.steamos_23.9.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/mesa-radv-23.3.0_devel.177466.steamos_23.9.1-1) - Up to date
- [jupiter-main/steam-jupiter-stable-1.0.0.78-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steam-jupiter-stable-1.0.0.78-1.2) - #261
- [jupiter-main/steam_notif_daemon-v1.0.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steam_notif_daemon-v1.0.1-1) - Up to date
- [jupiter-main/steamdeck-dsp-0.42-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steamdeck-dsp-0.42-1) - #261
- [jupiter-main/steamos-customizations-jupiter-20231122.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steamos-customizations-jupiter-20231122.1-1) - Up to date
- [jupiter-main/powerbuttond-2-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/powerbuttond-2-1) - Forked
- [jupiter-main/wireplumber-0.4.14.dev23-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/wireplumber-0.4.14.dev23-1) - Very downstream fork, unfortunately has to exist for now

### Nice to haves

Misc packages and changes to upstream packages for a better experience, see notes.

- [holo-main/maliit-keyboard-2.3.1-2.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/maliit-keyboard-2.3.1-2.1) - Disables Presage support, presumably big and unmaintained, we don't care about big
- [jupiter-main/bluez-5.69-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/bluez-5.69-1.2) - Some Valve specific patches there, investigate impact
- [jupiter-main/ds-inhibit-0.1.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/ds-inhibit-0.1.1-1) - Some kind of workaround for DualShock controllers, see if it's even used?
- [jupiter-main/holo-dmi-rules-1.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/holo-dmi-rules-1.0-1) - Currently applied but seemingly non-critical
- [jupiter-main/ibus-anthy-1.5.14-4](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/ibus-anthy-1.5.14-4) - Some IME stuff, investigate
- [jupiter-main/ibus-table-cangjie-lite-1.8.8-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/ibus-table-cangjie-lite-1.8.8-2) - More IME stuff
- [jupiter-main/networkmanager-1.42.6-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/networkmanager-1.42.6-1.1) - Patched with a workaround for 802.1x networks, investigate if we care
- [jupiter-main/plasma-remotecontrollers-5.27.10-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/plasma-remotecontrollers-5.27.10-1.1) - Reports device name as "Steam Deck" over CEC, extremely low priority
- [jupiter-main/steam-im-modules-jupiter.20220223-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steam-im-modules-jupiter.20220223-1) - Opens Steam keyboard as IME
- [jupiter-main/usbhid-gadget-passthru-0.1.2-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/usbhid-gadget-passthru-0.1.2-1) - seems to be intended for using the Deck as a controller on a PC, not working currently
- [jupiter-main/vpower-1.4.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/vpower-1.4.1-1) - Reports low battery conditions to Steam, forces shutdown on low battery

### Debug tools

Some tools that are clearly not intended to be used by end users, except maybe for bug reporting.

- [holo-main/drm_info-2.4.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/drm_info-2.4.0-1)
- [holo-main/vkmark-git-r133.30d2cd3-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/vkmark-git-r133.30d2cd3-2) - Vulkan benchmark, packaged in nixpkgs but old-ish
- [jupiter-main/gpu-trace-2.12-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/gpu-trace-2.12-1)
- [jupiter-main/renderdoc-minimal-1.30-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/renderdoc-minimal-1.30-1)

### Things we don't care about

Changes that are specific to SteamOS and/or the Arch base it's built on.

<details>
<summary>Details</summary>

- [holo-main/atomupd-daemon-git-0.20231006.2.r0.g0b004d9-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/atomupd-daemon-git-0.20231006.2.r0.g0b004d9-1) - Valve A/B update stuff
- [holo-main/casync-2.r227.g99559cd-4.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/casync-2.r227.g99559cd-4.1) - Valve A/B update stuff
- [holo-main/discover-5.27.8-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/discover-5.27.8-1.2) - Backported patch for Flatpak backend, we track latest Plasma
- [holo-main/e2fsprogs-1.47.0-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/e2fsprogs-1.47.0-1.2) - Patches to make filesystems compatible with old kernels, one is already in nixpkgs, other is not but probably non-critical
- [holo-main/filesystem-2021.12.07-1.10](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/filesystem-2021.12.07-1.10) - Arch stuff
- [holo-main/glibc-2.37-3.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/glibc-2.37-3.2) - Backports from 2.38, Nixpkgs is on 2.38
- [holo-main/gssproxy-0.9.1-2.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/gssproxy-0.9.1-2.1) - Patched for systemd-tmpfilesd, we don't have it at all
- [holo-main/holo-flatpak-tmpfiles-0.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/holo-flatpak-tmpfiles-0.1-1) - Flatpak config to work with Valve A/B stuff, not applicable
- [holo-main/holo-fstab-repair-0.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/holo-fstab-repair-0.1-1) - Valve SD card mount thingy, not applicable
- [holo-main/holo-keyring-20220203-4](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/holo-keyring-20220203-4) - Arch package signing stuff
- [holo-main/holo-zram-swap-0.1-0](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/holo-zram-swap-0.1-0) - Implemented as NixOS module
- [holo-main/iwd-2.7-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/iwd-2.7-1.2) - Backport from 2.8, nixpkgs update: https://github.com/NixOS/nixpkgs/pull/253153
- [holo-main/kdumpst-1.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/kdumpst-1.0-1) - Used by Valve's telemetry stuff, we probably don't care
- [holo-main/kmod-30-1.4](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/kmod-30-1.4) - Fixes Arch packaging to work on SteamOS
- [holo-main/kpmcore-23.04.2-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/kpmcore-23.04.2-2) - Backports fix specific to Valve's A/B setup
- [holo-main/lsb-release-2.0.r48.3cf5103-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/lsb-release-2.0.r48.3cf5103-1.1) - Reports SteamOS
- [holo-main/nfs-utils-2.6.3-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/nfs-utils-2.6.3-1.1) - Patched for systemd-tmpfilesd
- [holo-main/openssh-9.3p1-2.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/openssh-9.3p1-2.1) - Backported patches from 9.4
- [holo-main/paru-1.11.1-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/paru-1.11.1-1.1) - AUR helper
- [holo-main/plasma-desktop-5.27.5-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/plasma-desktop-5.27.5-1.1) - Backports
- [holo-main/plymouth-22.02.122-1.5](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/plymouth-22.02.122-1.5) - Patches don't look relevant
- [holo-main/podman-4.5.1-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/podman-4.5.1-1.1) - Packaging changes on the Arch side
- [holo-main/pyzy-1.1-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/pyzy-1.1-1.1) - Dependency of ibus-pinyin, no other reason
- [holo-main/rauc-1.8-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/rauc-1.8-1.1) - Valve A/B update stuff
- [holo-main/steamos-atomupd-client-git-r301.e0c2c4d-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-atomupd-client-git-r301.e0c2c4d-2) - Valve A/B update stuff
- [holo-main/steamos-efi-20231213.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-efi-20231213.1-1) - Valve A/B update stuff
- [holo-main/steamos-kdumpst-layer-1.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-kdumpst-layer-1.0-1) - Valve telemetry stuff
- [holo-main/steamos-log-submitter-0.4.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-log-submitter-0.4.1-1) - Valve telemetry stuff
- [holo-main/steamos-reset-20231006.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-reset-20231006.1-1) - Valve A/B update stuff
- [holo-main/steamos-systemreport-0.4-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-systemreport-0.4-1) - Valve telemetry stuff
- [holo-main/steamos-tweak-mtu-probing-1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/steamos-tweak-mtu-probing-1-1) - sysctl tweak, applied in modules
- [holo-main/systemd-253.5-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/holo-main/systemd-253.5-2) - Backport?
- [jupiter-main/alsa-ucm-conf-1.2.9-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/alsa-ucm-conf-1.2.9-1.2) - Patched for compatibility, we apply the same change differently
- [jupiter-main/breakpad-v2023.01.27-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/breakpad-v2023.01.27-1) - Only used by steamos-log-submitter, which we don't use
- [jupiter-main/f3-8.0-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/f3-8.0-2) - Included in nixpkgs
- [jupiter-main/flatpak-1.14.4-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/flatpak-1.14.4-2) - Valve ships 1.14 stable releases, Arch ships 1.15, we ship 1.14 as-is.
- [jupiter-main/holo-nix-offload-0.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/holo-nix-offload-0.1-1) - Duh
- [jupiter-main/jupiter-firewall-0.1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-firewall-0.1-1) - We have our own firewall
- [jupiter-main/jupiter-legacy-support-1.145-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-legacy-support-1.145-1) - Old and irrelevant workarounds
- [jupiter-main/jupiter-resolved-nomdns-1.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-resolved-nomdns-1.0-1) - According to comment, only used by the devkit stuff
- [jupiter-main/jupiter-steamos-log-submitter-1-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/jupiter-steamos-log-submitter-1-1) - Valve telemetry stuff
- [jupiter-main/mesa-23.3.0.179668.radeonsi_3.6.0-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/mesa-23.3.0.179668.radeonsi_3.6.0-1) - patched Mesa for OpenGL stuff, we're currently using vanilla nixpkgs Mesa + the frame limiter patch, update to 23.3 pending staging-next merge
- [jupiter-main/sddm-wayland-v0.19.0.valve4.d19813cb03c7d71b896aead28e5285bc131500a9-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/sddm-wayland-v0.19.0.valve4.d19813cb03c7d71b896aead28e5285bc131500a9-1) - We're using greetd
- [jupiter-main/steamdeck-kde-presets-0.21-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/steamdeck-kde-presets-0.21-1) - Doesn't really work with NixOS user management, maybe revisit in the far future?
- [jupiter-main/ttf-twemoji-default-13.1.0-2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/ttf-twemoji-default-13.1.0-2) - Enables the font by default, we don't want that
- [jupiter-main/udisks2-2.9.4-1.2](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/udisks2-2.9.4-1.2) - Backports from 2.10, we already have those
- [jupiter-main/upower-0.99.15.jupiter-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/upower-0.99.15.jupiter-1.1) - Disables tests, does nothing else
- [jupiter-main/xdg-desktop-portal-1.17.1-1.0](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/xdg-desktop-portal-1.17.1-1.0) - 1.18 in nixpkgs
- [jupiter-main/xdg-desktop-portal-gtk-1.15.1-1.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/xdg-desktop-portal-gtk-1.15.1-1.1) - packaging changes no longer useful
- [jupiter-main/xdg-desktop-portal-kde-5.27.8-3.1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/xdg-desktop-portal-kde-5.27.8-3.1) - backports
- [jupiter-main/zenity-light-3.32.0+55+gd7bedff6-1](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/tree/jupiter-main/zenity-light-3.32.0+55+gd7bedff6-1) - Arch packaging changes
</details>

**Comment by K900** [comment]
Redacted, see main issue for up to date status.

**Comment by samueldr** [comment]
(Closing, @K900 has been tracking changes with the [manifest tooling](https://github.com/Jovian-Experiments/Jovian-NixOS/commits/development/support/manifest), and this issue has not been updated.)
