### ISSUE TITLE
Initial installation requires internet connection before the ability to configure Wi-FI

### ISSUE THREAD

**Issue by misuzu** [Jovian-Experiments/Jovian-NixOS#134]
The initial setup is not possible without internet connection. Fast solution is to use USB-Ethernet dongle which might not be available.

Here are the steps I've used to reproduce this issue:

1. Build an iso (https://github.com/NixOS/nixpkgs/pull/246441 and https://github.com/Jovian-Experiments/Jovian-NixOS/pull/127 might be required) with `jovian.steam.autoStart` enabled
2. Boot that iso with copytoram to be able to connect usb devices
3. Observe the issue ![IMG_20230813_120222](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/248143/682a8881-9b17-4cd0-bd1f-d6ec6ca0bc25)

[journal.log](https://github.com/Jovian-Experiments/Jovian-NixOS/files/12329154/journal.log) (USB-Ethernet dongle was connected at Aug 13 12:04:35, the ethernet cable was connected at Aug 13 12:06:03)

How to build the same iso:
First we need https://github.com/NixOS/nixpkgs/pull/246441
```
# in the nixpkgs tree: checkout #246441 and rebase it on top of nixos-unstable
nix run nixpkgs#gh -- pr checkout 246441
git rebase ce5e4a6ef2e59d89a971bc434ca8ca222b9c7f5e # current nixos-unstable
```
Now we can use that to build the iso
```
git clone https://gitlab.com/misuzu/nixos-configuration.git && cd nixos-configuration
# override nixpkgs with the local copy
nix flake lock --override-input nixpkgs /path/to/nixpkgs
nix build -L --print-out-paths .#nixosConfigurations.jovian-iso.config.system.build.isoImage
```

**Comment by samueldr** [comment]
@misuzu I'll try to try later, but can you try also enabling NetworkManager in the iso? This is just a gut feeling here.

Assuming this was the minimal iso where you added `jovian.steam.autoStart`, I'm not sure what the minimal iso uses these days for networking, but I'd be willing to bet it's not NetworkManager.

And relatedly, I wonder if that updater applet has some bad assumptions under these conditions.

If that fixes it, then the solution will be to warn/assert on NetworkManager being missing, I suppose.

Though uh, it looks like we're probably doing it already?

 - https://github.com/Jovian-Experiments/Jovian-NixOS/blob/23ba73bfb6b6cc9fe51c64bdda54eebc212e6fdf/modules/steam.nix#L374-L376

**Comment by misuzu** [comment]
> can you try also enabling NetworkManager in the iso?

Just booted this iso again - NetworkManager is there

**Comment by misuzu** [comment]
> Assuming this was the minimal iso where you added `jovian.steam.autoStart`, I'm not sure what the minimal iso uses these days for networking, but I'd be willing to bet it's not NetworkManager.

I've added instructions on how to build the exact iso I've used (though if you want to try it, it's better to add your ssh key to `common/users.nix`, just in case). It's pretty much the same config I use on my deck, but in iso

**Comment by samueldr** [comment]
Thank you, having a complete "product" to test from will definitely help!

**Comment by samueldr** [comment]
Reproduced. Confirmed.

Cause TBD, but now at least I have a system to check that on.

* * *

~~It might actually affect the steam session outright, not just with OOBE... I accidentally booted into my system without a connection active, and the update checker thing kept "bootlooping", but without the error message... Though I haven't investigated that *yet*. It might have been something else (?)~~ Probably not(?); could not reproduce.

**Comment by samueldr** [comment]
So it ***really*** is about the connection (unsurprisingly)...

 - https://gist.github.com/samueldr/1e69196281e27ccb4d064983c0bea1f1

I wonder if this is relevant:

```
[2023-08-16 03:54:54] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
```

If you're "opted" into a "new" beta via CLI, it might not be able to re-use the existing steam as a starting point?

* * *

Probably not that directly, since the beta name is the same... and here's my working offline boot:

```
[2023-08-16 00:16:00] Opted in to client beta 'steamdeck_publicbeta' via beta file
You are in the 'steamdeck_publicbeta' client beta.
```

The first difference I see (mine clearly shows it can't access manifests for download) is here:

```
[2023-08-16 03:54:58] Unable to read and verify install manifest /home/deck/.local/share/Steam/package/steam_client_steamdeck_stable_ubuntu12.installed
```

* * *

***sus***

 - https://github.com/Jovian-Experiments/PKGBUILDs-mirror/blob/jupiter-main/steam-jupiter-oobe/steam-jupiter.sh

* * *

I can see that yes, that `BootStrapperInhibitAll` flag prevents the updater on my personal system.

But... that seems hard to handle... hmmmmm....

> Also see steam-jupiter-stable's variant of this script, which looks for this marker

Thank you good person, leaving useful comments in that script!

:eyes: 

Oh, hey, hello you

 - https://github.com/Jovian-Experiments/PKGBUILDs-mirror/blob/9402c2c4ca5e7fa7735a506e3fd9c73d8bbde0f8/steam-jupiter.sh#L11-L35
