### ISSUE TITLE
[Bug] The steam-deck ui won't load

### ISSUE THREAD

**Issue by dnkmmr69420** [Jovian-Experiments/Jovian-NixOS#147]
I've tested this on both qemu vm and virtualbox and I get that black tty with nothing on it. Does this mean it will happen on the steam deck?

**Comment by samueldr** [comment]
No, gamescope is AFAIK not expected to run without full gpu drivers.

I don't think we've had anyone recently have any issues with it on the Steam Deck using the recommended configurations.

**Comment by dnkmmr69420** [comment]
ok thats good to hear. If I get the steam deck, I will probably use jovian-nixos so I can use stuff like waydroid and have podman for distrobox

**Comment by K900** [comment]
Not really something we can do anything about, so closing.
