### ISSUE TITLE
How do you use the option `jovian.steam.desktopSession`

### ISSUE THREAD

**Issue by dnkmmr69420** [Jovian-Experiments/Jovian-NixOS#149]
Like can someone give me an example of having the desktop session being KDE wayland?

`jovian.steam.desktopSession`

**Comment by samueldr** [comment]
The session name is `"plasmawayland"`.

**Comment by dnkmmr69420** [comment]
oh ok so like this?

```nix
jovian.steam.desktopSession = plasmawayland;
```

**Comment by dnkmmr69420** [comment]
or like this?

```nix
jovian.steam.desktopSession = "plasmawayland";
```

**Comment by samueldr** [comment]
You could try either, and see, but it's the latter, since otherwise it would refer to the variable name `plasmawayland`, which wouldn't be a thing in scope.

**Comment by IceDBorn** [comment]
Does this work when autologin is not enabled? Also, I tried enabling autologin and set `jovian.steam.desktopSession` to `Hyprland` and `hyprland`, but it just boots back to the steam deck UI.

**Comment by b-m-f** [comment]
> Does this work when autologin is not enabled? Also, I tried enabling autologin and set `jovian.steam.desktopSession` to `Hyprland` and `hyprland`, but it just boots back to the steam deck UI.

I experience the same when setting desktopSession to `gnome` with:
```nix
{ ... }: {

  services.xserver.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  jovian.steam = {
    enable = true;
    autoStart = true;
    user = "user";
    desktopSession = "gnome";
  };
}

```

Edit:

```nix
{ ... }: {

  services.xserver.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;

  jovian.steam = {
    enable = true;
    autoStart = true;
    user = "user";
    desktopSession = "plasma";
  };
}

```
Works fine. So it should not be anything else in my config.
