### ISSUE TITLE
Max volume is lower then Stock os 

### ISSUE THREAD

**Issue by ghost** [Jovian-Experiments/Jovian-NixOS#157]

**Comment by ghost** [comment]
I think this could be fixed with a filter chain but I am struggling to get it setup (pipewire is confusing 😭)

**Comment by ghost** [comment]
add this to /etc/pipewire/pipewire.conf.d/
```
    context.modules = [
        {   name = libpipewire-module-filter-chain
            args = {
                node.description =  "Boost Filter"
                media.name =  "Boost Filter"
                filter.graph = {
                    nodes = [
                        {
                            type = builtin 
                            name = mixer 
                            label = mixer 
                            control = {
			   	"Gain 1" = 3.5
				"Gain 2" = 3.5
                            }
                        }
		
                    ]
		   inputs = ["mixer:In 1" "mixer:In 2"]
		   outputs = ["mixer:Out"]
                }
                capture.props = {
                    node.name = "boost.sink"
                    node.passive = true
		   media.class = Audio/Sink
                }
            }
        }
    ]
```
`wpctl set-default <sink's id>`

**Comment by ghost** [comment]
@samueldr is something that I should make into a pr ? At least until its understood why the audio is quiet

**Comment by toast003** [comment]
Did some research and I think [these files](https://gitlab.com/evlaV/jupiter-hw-support/-/tree/master/usr/share/alsa/ucm2/conf.d/acp5x?ref_type=heads) make the speakers loud enough, although I haven't tested it yet

**Comment by toast003** [comment]
Took a look at [modules/steamdeck/sound.nix](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/modules/steamdeck/sound.nix), and environment variables are set up with the location of the files I linked earlier, but they don't seem to be taking effect

Maybe putting them in a package (making them show up in /run/current-system/) might fix this?

**Comment by milikhin** [comment]
I've noticed that SteamOS 3.5 Preview release increases volume on my Deck significantly.

What solved the issue for me was taking a backup of ALSA settings with `alsactl --file asound.state store` under SteamOS 3.5 (or under NixOS right after installation on top of SteamOS 3.5) and then restoring them under NixOS when the max volume eventually becomes lower with `alsactl --file asound.state restore`.

I believe it's also possible to tweak setting for `acp5x` sound card manually using the `alsamixer`.

Stock SteamOS 3.5 settings are the following:
![1](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/13817735/7d7cb87b-eb77-4dde-9c20-a0764ef5f51a)
![2](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/13817735/9b8d88ff-823f-400a-90b6-889115bfba32)
![3](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/13817735/3931d8d5-f965-4c6e-aeea-2d8e261216e8)

alsactl settings backup: [asound.state](https://github.com/Jovian-Experiments/Jovian-NixOS/files/12877348/asound.txt)

**Comment by pongo1231** [comment]
`alsactl --file /home/pongo/asound.state restore` gives me the following on NixOS
```
alsa-lib main.c:846:(execute_sequence) exec '/bin/rm -rf /var/lib/alsa/card1.conf.d' failed (exit code 1)
``` 

In case anyone else also hits this, what worked for me is running the command in a container to then manually copy the resulting [ctl-remap.conf](https://github.com/Jovian-Experiments/Jovian-NixOS/files/12908269/ctl-remap.conf.txt) to `/var/lib/alsa/card1.conf.d/`.

**Comment by milikhin** [comment]
> `alsactl --file /home/pongo/asound.state restore` gives me the following on NixOS

Oh, totally forgot about it, as a workaround to make `alsactl` work I've also created symlinks for `/run/current-system/sw/bin/rm` and `/run/current-system/sw/bin/mkdir` at `/bin`

**Comment by pongo1231** [comment]
Is that file perhaps something that should be shipped by default if `jovian.devices.steamdeck.enableSoundSupport = true`?

**Comment by K900** [comment]
Please test https://github.com/Jovian-Experiments/Jovian-NixOS/pull/187

**Comment by pongo1231** [comment]
Works on my end. After deleting `/var/lib/alsa/card1.conf.d/ctl-remap.conf`, applying #187 and rebooting the volume is still as it should be.

**Comment by toast003** [comment]
https://github.com/Jovian-Experiments/Jovian-NixOS/pull/187 doesn't seem to change the max volume for me

**Comment by K900** [comment]
Try running `spa-acp-tool -c 1 spr 1`

**Comment by toast003** [comment]
That did it!
It doesn't seem to persist reboots tho

**Comment by K900** [comment]
Should now survive reboots (after #187).
