### ISSUE TITLE
Make the session types use `displayManager.sessionData.sessionNames` for validation

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#163]
Right now there's a real issue where users are not aware of the actual session name to use, and end-up unable to select their sessions.

The type should follow the `defaultSession` type in Nixpkgs.

 - https://github.com/Jovian-Experiments/Jovian-NixOS/blob/d31a25e74b1bb7df342c0a53eeac4d4f91ea22b1/modules/steam/autostart.nix#L34
 - `config.services.xserver.displayManager.sessionData.sessionNames`
 - https://github.com/NixOS/nixpkgs/blob/f78122df472e2871b2623b82b8c38a3e9f2807ea/nixos/modules/services/x11/display-managers/default.nix#L297-L305

This would solve #149, mostly.

**Comment by pongo1231** [comment]
Should be solved by #201, no?
