### ISSUE TITLE
Trying to get keyboard to work at initrd

### ISSUE THREAD

**Issue by dpolakovics** [Jovian-Experiments/Jovian-NixOS#171]
Hello,

i'm trying to get my usb keyboard to work at initrd with the steamdeck.
Without the following line it works:  
jovian.devices.steamdeck.enable = true;

It seems like no usb device is working at initrd, except the gamepad.

Maybe i'm importing the wrong kernel modules, but i tried the kernel modules which are also in nixpkgs.

Best regards,
Dominik

**Comment by Ninlives** [comment]
Do you have any progress on this issue?

**Comment by dpolakovics** [comment]
Ah yes,

it was an issue with the valve kernel.
When i use the normal one it works:
boot.kernelPackages = lib.mkForce pkgs.linuxPackages_latest;
