### ISSUE TITLE
Decky-loader-frontend-deps doesn't build because the hash is wrong

### ISSUE THREAD

**Issue by toast003** [Jovian-Experiments/Jovian-NixOS#173]
The npm hash seems to have changed, as changing it to the hash nix tells you makes it build successfully 

Here's the error
```
error: hash mismatch in fixed-output derivation '/nix/store/vycrrcjkbk49wingi8bf5imp8rjlbyx1-decky-loader-frontend-deps-2.10.4.tar.gz.drv':
         specified: sha256-FyrFVHRCJX/PUGilLpiRaQwcDUO9edNWCvN/3ugVejQ=
            got:    sha256-tJ/psoByV7ySrE/Z4K0mGZAy2clsiiruUZ8tICUhDM8=
error: 1 dependencies of derivation '/nix/store/qwk9n95k96l90h9gpgrhh0mnil8dfmdz-decky-loader-frontend-2.10.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dbf8jw2bh4sp01n1398y82ib95hj3ry0-decky-loader-2.10.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lr0i94mj0hz6l6xnhr4kf0f32sdhk4al-unit-decky-loader.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qcjjnvmc4xbjrp1301r0dfqijn5p5bf3-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rvs39vmnfs7lnpw3kgx8y12748062r60-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/58ig9c4agbm4qjhy8c7qwk0g7snfffhr-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w0dyrbkxjl6bl3k8xsp4zbsi2ycxk8cz-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k90svn8r4znr9jvxnjgs1fv29x1nn39i-nixos-system-SteamDeck-23.11.20230927.8a86b98.drv' failed to build
error: 2 dependencies of derivation '/nix/store/s2d7qck93vvyih5qhig89hxiy83r3icr-nixos-system-SteamDeck-23.11.20230927.8a86b98.drv' failed to build
```

**Comment by K900** [comment]
It seems to be weirdly unreproducible sometimes, but I couldn't identify why.

**Comment by toast003** [comment]
Yeah, trying to build it on my server and PC fails, while my steam deck build it just fine

Weird that it isn't consistently reproducible tho, you would think these things would not happen with Nix :thinking:

**Comment by K900** [comment]
I wonder if it has something to do with filesystems? Case normalization somewhere maybe?

**Comment by toast003** [comment]
Not sure, I use btrfs on everything I own

**Comment by K900** [comment]
Can you still reproduce this? I still can't...

**Comment by toast003** [comment]
Yes, although it has the exact same wrong hash as my first comment even though decky loader has updated :thinking: 
```
building the system configuration...
error: hash mismatch in fixed-output derivation '/nix/store/0zciksvfar4gm67aypsfxs8k7fxndyfh-decky-loader-frontend-deps-2.10.5.tar.gz.drv':
         specified: sha256-FyrFVHRCJX/PUGilLpiRaQwcDUO9edNWCvN/3ugVejQ=
            got:    sha256-tJ/psoByV7ySrE/Z4K0mGZAy2clsiiruUZ8tICUhDM8=
error: 1 dependencies of derivation '/nix/store/l207a7arwcn8j4allvgpsiskbyz7wk5x-decky-loader-frontend-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9j60qqs57yk77876fpxz8nxwq2ar8y3s-decky-loader-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iqfhifxswishwlg0fx2xwni7rfvanr2r-unit-decky-loader.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hbmp0lhh8c6p6np3jgl232a9a5vl1pwh-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rndijs5ajw0d6r6ydrx24mj79wfrc22b-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/faamzkw8q2cv1ci64fjaij7idkfjq8lm-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xhb7xx9cixzhccd6msv8369ailvpw9sz-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hi98fz4ygjw6p0f6bdf7c4x4hs7akb04-nixos-system-SteamDeck-23.11.20231016.ca012a0.drv' failed to build

```
I really do not understand this at all

**Comment by K900** [comment]
This is kinda expected, the frontend part wasn't touched in that update at all. Can you run it with `--keep-failed` and then upload the build directory you got in /tmp?

**Comment by toast003** [comment]
Sure 
http://temp.sh/zsvej/failed-build.tar.gz

**Comment by K900** [comment]
What nixpkgs and Jovian revisions are you building this with?

**Comment by K900** [comment]
Actually, another thing: can you try setting the hash in the Jovian repo to the one you're getting, build it, and upload the actual tarball you're getting in the Nix store?

**Comment by toast003** [comment]
> What nixpkgs and Jovian revisions are you building this with?

Jovian is 2965d86926177af95af615a09138e0aaaaec56fa, and nixpkgs is ca012a02bf8327be9e488546faecae5e05d7d749

**Comment by toast003** [comment]
> Actually, another thing: can you try setting the hash in the Jovian repo to the one you're getting, build it, and upload the actual tarball you're getting in the Nix store?

(I'm guessing you're talking about the source tarball, not a tarball with the end result)
http://temp.sh/QYOmC/anpscsbydavz40csb8zvb7f4qhybvhxd-decky-loader-frontend-deps-2.10.5.tar.gz

**Comment by K900** [comment]
Can you test https://github.com/Jovian-Experiments/Jovian-NixOS/pull/190 ?

**Comment by toast003** [comment]
Yup, it builds now

**Comment by jpgrego** [comment]
Hello @K900 , this seems to be occurring again, probably due to the version bump you did 2 weeks ago.

```
error: hash mismatch in fixed-output derivation '/nix/store/7y0yyq83jwlif6b7d71fpih9vwdi6mlh-decky-loader-frontend-deps-2.10.10.tar.gz.drv':
         specified: sha256-4AC+mza7ya3wqVQYUe+wT311BT21aLHcBDBkpCxc3ZU=
            got:    sha256-ksDgEndplS/ytTIoBakqad2YdpDHilf2zpVwQeqD28E=
```

**Comment by K900** [comment]
I'll have to recheck.

**Comment by jpgrego** [comment]
Replacing the hash for the one obtained above works, as expected. If it's just a matter of updating the hash I'm happy to submit a pull request but it is odd that the hash simply changed like that.

**Comment by jpgrego** [comment]
Please disregard my first message, I believe it was a problem on my end. I was mixing unstable nixpkgs with stable home-manager. After fixing that issue it works fine.

Apologies, still a newbie with nix :)
