### ISSUE TITLE
Audio profile switching under steam-session seems broken

### ISSUE THREAD

**Issue by pongo1231** [Jovian-Experiments/Jovian-NixOS#182]
Switching from speakers to headphones output requires me to select a different output device in Steam settings and switch back afterwards. However going back from headphones to speakers results in audio output still attempting to go through the headphones and until headphones are plugged back in forces me to the "External Device" output device until Steam is restarted.

Only relevant log in `journalctl -xe` I could find is the following:
```
wireplumber[1925]: Failed to enable ucm device Headphones
```

Steps to reproduce:
1. Start steam-session
2. Play audio through speakers, it should work
3. Plug in headphones
4. Audio still plays through speakers, go to Audio page in Steam settings and switch output device to "External device" and back to "Speakers"
5. Audio should play through headphones now
6. Unplug headphones, no audio through speakers even with the trick above and output device is forced to "External device" until Steam is restarted

**Comment by pongo1231** [comment]
Tried older jovian and nixpkgs revs along with older kernel versions and the issue persists. I can only assume this seems to stem from a Steam update itself? Would make sense as to why this only occurs in steam-session then.

Also minor unrelated thing I stumbled upon during testing, [this file](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/pkgs/jupiter-hw-support/default.nix#L87) is unused nowadays and could be cleaned up - didn't think it'd warrant opening up a PR.

**Comment by K900** [comment]
It is in fact used.

**Comment by pongo1231** [comment]
Looking at the derivation pointed to by the ALSA_CONFIG_UCM2 envvar, it seems to use alsa-ucm-conf's ucm.conf instead. Only jupiter-hw-support's conf files from [conf.d/acp5x/](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/modules/steamdeck/sound.nix#L10) are applied here so it goes unused, unless I'm missing something. Also I tried overriding that file with jupiter-hw-support's version but that simply broke all sound for me.

**Comment by K900** [comment]
Oh, sorry, got things mixed up there for a bit. A PR to remove that stuff would be absolutely welcome.

**Comment by K900** [comment]
Can you test https://github.com/Jovian-Experiments/Jovian-NixOS/pull/187 ?

**Comment by pongo1231** [comment]
Unfortunately still occurs after applying #187 and rebooting

**Comment by K900** [comment]
It sounds like Pipewire might not be picking up the config properly for some reason, I'm looking into it.

**Comment by toast003** [comment]
~~Applied https://github.com/Jovian-Experiments/Jovian-NixOS/pull/187 and it's working now~~

Nevermind, it does switch to headphones when I plug them in, but I can't tell it where to output sound though steam

**Comment by pongo1231** [comment]
Gave pulseaudio a try as well with
```
services.pipewire.enable = false;
hardware.pulseaudio.enable = true;
```
and similar behavior occurs there as well: playing audio through speakers and changing volume works just fine, when plugging in headphones it only switches output when re-selecting the Speakers option in Steam and the volume state only applies to speakers; changing volume does nothing for headphone output. On a desktop session everything works fine, same as pipewire.

**Comment by pongo1231** [comment]
After applying #187 again with the newest commits wireplumber stopped complaining in the logs and I can now consistently switch between speaker and headphones output. However going from speaker to headphones and back to speaker output Steam still gets "stuck" on the headphones output device; whilst the audio successfully plays through speakers Steam still displays and applies changes to the volume state for the headphones output, whilst also not applying changes to the Output Device option as was the case previously.

**Comment by K900** [comment]
Well, that's an improvement. I guess now we just have to sniff the Pipewire bus and see what Steam is doing... This would have been a lot easier if I had a set of wired headphones, tbh.

**Comment by pongo1231** [comment]
Interesting, just switched my nixpkgs flake input to `nixos-23.05` (commit [60b9db998f71ea49e1a9c41824d09aa274be1344](https://github.com/NixOS/nixpkgs/commit/60b9db998f71ea49e1a9c41824d09aa274be1344)) and while the issue with the output device not being changeable in settings still persists, I can switch between headphones and speaker output and consistently change the volume of the current output completely fine again. This suggests a regression introduced somewhere in unstable.

**Comment by K900** [comment]
It may just be some Pipewire bug. 0.3.83 is in staging-next now, so we'll see in a bit.

**Comment by pongo1231** [comment]
Gave the version in staging-next a try and sadly it still occurs (assuming setting `pipewire.package` and importing the module from staging-next is enough to include all the changes). Will try to find the commit in nixpkgs which introduced this issue.

**Comment by pongo1231** [comment]
I've been able to pinpoint it to [this commit](https://github.com/NixOS/nixpkgs/commit/9e7a159d8c15df3a3ce9a2349ca29e7129710594) which is a mere pipewire version bump (0.3.76 to 0.3.77). So this just seems to be a regression coming from pipewire itself. From what I can see SteamOS ships with 0.3.62 so it makes sense this issue doesn't occur there.

**Comment by K900** [comment]
Does 0.3.76 work entirely correctly, or does the switching through Steam still not work?

**Comment by pongo1231** [comment]
Actually now I can't select `External device` at all but I can switch between `Speakers` and `Default (Speakers)` output in Steam. It's a bit janky as in output not switching automatically to headphones occasionally after switching between those two but changing the output device whilst headphones are plugged in properly picks up the headphones again. This could very well just be a Steam bug.

**Comment by imadnyc** [comment]
Would downgrading to 0.3.62 do anything? And the problem currently is that when you plug the headphones in, it doesn't automatically switch, but you can change it fine manually when it's plugged in and you switch it through steam settings? Apparently 0.3.62 was never packaged in nixpkgs, so I'll maybe see and try an overlay when I'm home. https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=pipewire .

**Comment by pongo1231** [comment]
> Would downgrading to 0.3.62 do anything?

Would be worth a try.

> And the problem currently is that when you plug the headphones in, it doesn't automatically switch, but you can change it fine manually when it's plugged in and you switch it through steam settings? 

With 0.3.76, correct. I do remember that being an issue on SteamOS also when I last used it however - which was more than half a year ago.

> Apparently 0.3.62 was never packaged in nixpkgs, so I'll maybe see and try an overlay when I'm home. https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=pipewire .

I'd set `services.pipewire.package` instead to avoid redundantly rebuilding other derivations taking pipewire as an input.

**Comment by imadnyc** [comment]
I finally got the chance to do some testing, but reproducing it is kind of internmittent. I got the bug to happen only once, which I couldn't fix at all by selecting any of the options. Then, I restarted, and the bug was still present. After, I selected speakers, and it now switched between headphones and speakers as you expect - when you plug it in, it switches to headphones. But now I can't force speakers - if headphones are plugged in, it always plays through it, even if I select speakers. Now, even if I restart, I can't get the bug at all ever. Does anyone know if selecting speakers while headphones are plugged in still plays audio through headphones? This is through the latest pipewire - testing 0.3.63 right now, and if that doesn't fix it, will do 0.3.62 because 63 is packaged in nixpkgs.

**Comment by K900** [comment]
Can someone try https://github.com/Jovian-Experiments/Jovian-NixOS/pull/216 ?

**Comment by pongo1231** [comment]
It still gets put into the same weird state after plugging and unplugging with the latest pipewire and #216

Edit: Additionally pipewire 0.3.76 breaks with that PR applied. Seems like it requires a library from one of the dependencies only available in a newer rev.

```
pipewire[76678]: default: failed to load plugin '/nix/store/v2bds7zsxn929nqy5xj7fpp82h4aky31-rnnoise-plugin-1.03/lib/ladspa/librnnoise_ladspa.so': No such file or directory
pipewire[76678]; mod.filter-chain: can't load graph: No such file or directory
pipewire[76678]: pw.conf: 0x561857c4ae00: could not load mandatory module "libpipewire-module-filter-chain": No such file or directory
pipewire[76678]: default: failed to create context: No such file or directory
```

**Comment by toast003** [comment]
Tried #216 and the only change I noticed is a new device (Speakers (Tuned)) showing up that doesn't work

**Comment by samueldr** [comment]
The changes #216 brings in should only affect the OLED model.

**Comment by K900** [comment]
Not necessarily, there's some upstream wireplumber stuff in there too, but it doesn't seem related.

**Comment by toast003** [comment]
Think this is fixed now, installed jovian on my gpd win max 2 and I can switch between my bluetooth headphones and the speakers just fine

**Comment by pongo1231** [comment]
Can confirm I'm not hitting the issue anymore on latest pipewire and jovian
