### ISSUE TITLE
desktopsession check contradictory

### ISSUE THREAD

**Issue by sg-qwt** [Jovian-Experiments/Jovian-NixOS#221]
I use deck as console without desktop seesion
    
1.  If I put `jovian.steam.desktopSession = "steam-wayland";`, I get an error runnning `nix flake check`
```
       error: Desktop session 'steam-wayland' not found.
       Valid values for 'jovian.steam.desktopSession' are:

       If you don't want a desktop session to switch to, remove 'jovian.steam.desktopSession' from your config.
 ```
 2. If I following the above advice removing `jovian.steam.desktopSession`, I still get a big warning contradictory:
 ```
 This means that using the Switch to Desktop function in Gaming Mode will
relaunch Gaming Mode.

Set jovian.steam.desktopSession to the name of a desktop session, or "steam-wayland"
to keep this behavior.

 ```
 
 IMO, it's probably best to ask user set desktopSession to steam-wayland explicitly in the first case.

**Comment by K900** [comment]
The warning should be updated, the correct session name is `gamescope-wayland`.

**Comment by sg-qwt** [comment]
> The warning should be updated, the correct session name is `gamescope-wayland`.

Actually since we check desktopSession validity already, it wouldn't make sense to warn on default value I think. That's why I proposed to remove that warning completely.

**Comment by sg-qwt** [comment]
Unless we want to go all the way to update the check to include "gamescope-wayland", and set desktopSession default to  "gamescope-wayland" instead of null? but in that pr it explicitly removed it from list. "lib.lists.remove "gamescope-wayland" 

So removing the second warning completely would probably be the easier option here.

**Comment by K900** [comment]
I don't want to lose the warning, because then people will get confused by the default behavior.

**Comment by sg-qwt** [comment]
> I don't want to lose the warning, because then people will get confused by the default behavior.

yes, default behavior could confuse people. check #225 instead
