### ISSUE TITLE
Move HandlePowerKey into `jovian.steamdeck`

### ISSUE THREAD

**Issue by appsforartists** [Jovian-Experiments/Jovian-NixOS#234]
`HandlePowerKey` is disabling default power button behavior in favor of the Deck's power button tools, but those tools don't run on non-Decks.

https://github.com/Jovian-Experiments/Jovian-NixOS/blob/ab1bdc6a387c7a614f53fe78a77f51e3f234820e/modules/steam/steam.nix#L38-L41

cc @K900

**Comment by samueldr** [comment]
The Steam Deck powerbuttond should be pretty agnostic to "any modern ACPI system"...

 - https://github.com/Jovian-Experiments/powerbuttond/blob/c44da1812be8c7d95863d1e3fecbf0d1b2b4cd71/powerbuttond.c#L22-L23

```
~ $ grep . /sys/class/dmi/id/board_{vendor,name}
/sys/class/dmi/id/board_vendor:Star Labs
/sys/class/dmi/id/board_name:StarBook

~ $ ls -l /dev/input/by-path/platform-i8042-serio-0-event-kbd
lrwxrwxrwx 1 root root 9 Oct 29 18:05 /dev/input/by-path/platform-i8042-serio-0-event-kbd -> ../event1

```

It should be working on non-steamdeck too, but it wouldn't surprise me if there are some subtleties on some platforms where it won't.

**Comment by samueldr** [comment]
First thing we should be doing is using the discrete option so it can be `mkForce`'d away by end-users, when needed, and at the same time, adding a discrete option `powerbuttond.enable`.

 - https://search.nixos.org/options?channel=unstable&query=services.logind.powerKey

**Comment by appsforartists** [comment]
That was my first attempt.  I can only find the Legion Go's power button at `event2`.  I couldn't figure out if there was a better way to identify it and link it to where `powerbuttond` expects.

```
[nix-shell:~]$ sudo libinput debug-events
-event0   DEVICE_ADDED            Video Bus                         seat0 default group1  cap:k
-event2   DEVICE_ADDED            Power Button                      seat0 default group2  cap:k
-event3   DEVICE_ADDED            NVTK0603:00 0603:F001             seat0 default group3  cap:t  size 114x183mm ntouches 10 calib
-event4   DEVICE_ADDED            Ideapad extra buttons             seat0 default group4  cap:k
-event1   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group5  cap:k
-event2   KEYBOARD_KEY            +0.000s	KEY_POWER (116) pressed
 event2   KEYBOARD_KEY            +0.000s	KEY_POWER (116) released

ls -la /dev/input/by-path/
total 0
drwxr-xr-x 2 root root 180 Nov 19 20:31 .
drwxr-xr-x 4 root root 400 Nov 19 20:31 ..
lrwxrwxrwx 1 root root  10 Nov 19 20:14 pci-0000:c2:00.3-usb-0:3:1.0-event-joystick -> ../event10
lrwxrwxrwx 1 root root   6 Nov 19 20:14 pci-0000:c2:00.3-usb-0:3:1.0-joystick -> ../js0
lrwxrwxrwx 1 root root  10 Nov 19 20:14 pci-0000:c2:00.3-usbv2-0:3:1.0-event-joystick -> ../event10
lrwxrwxrwx 1 root root   6 Nov 19 20:14 pci-0000:c2:00.3-usbv2-0:3:1.0-joystick -> ../js0
lrwxrwxrwx 1 root root   9 Nov 19 20:14 platform-AMDI0010:03-event -> ../event3
lrwxrwxrwx 1 root root   9 Nov 19 20:14 platform-i8042-serio-0-event-kbd -> ../event1
lrwxrwxrwx 1 root root   9 Nov 19 20:14 platform-VPC2004:00-event -> ../event4

```

**Comment by zhaofengli** [comment]
I have the same issue on my Loki Zero, where the power button events are not exposed via `/dev/input/by-path/platform-i8042-serio-0-event-kbd`. Currently I use [an alternative implementation of powerbuttond](https://github.com/zhaofengli/Jovian-NixOS/commit/680a964df898dda3a42b214e9fabbde34c0d95c8) ([hacky integration](https://github.com/zhaofengli/Jovian-NixOS/commit/7e4d01c08157fc27baa065387650b8234955382f)) that's more customizable. Alternatively, we can patch `powerbuttond` directly.

**Comment by appsforartists** [comment]
I had also wondered about patching `powerbuttond`, but I didn't know if that was safe.  As I understand it, `/dev/input/event2` can't be trusted to be a stable path (always pointing to the power button), but I'd be happy to be wrong about that.

**Comment by samueldr** [comment]
Right, so `platform-i8042-serio-0-event-kbd` exists, but isn't what the power button is connected to...

***sigh*** (but unsurprising).

It sure would be better if the implementation of `powerbuttond` looked at all inputs and listened to any exposing `KEY_POWER`.

An alternative first pass would be to make it take an argument for an alternative path for the power key input device.
