### ISSUE TITLE
Support for modding

### ISSUE THREAD

**Issue by ShalokShalom** [Jovian-Experiments/Jovian-NixOS#253]
I know this might be a liiitle bit out of the scope of this project - and I feel it would create an incentive to use Jovian over the default OS, and generally contribute good PR to the project. 

Adding modding support for some games specifically, out of the box or at least via an opt-in configuration option, would help players, who are new to NixOS. 

Here is [one guide](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/users-modding-cyberpunk-2077/modding-on-linux), to show which steps lead to this success.

**Comment by K900** [comment]
This is definitely extremely out of scope for this project.

**Comment by ShalokShalom** [comment]
This seems like a bit rushed. 

This project is all about a gaming device, as is this suggestion.

I understand it would be something, the team does not want to work on, but calling it extremely out of scope and closing it immediately seems a bit insensitive.

**Comment by K900** [comment]
As one of the maintainers of this project, I can absolutely tell you that this is not something the team wants to work on, _or_ something the team wants to be part of the project at all.
