### ISSUE TITLE
Steam Deck screen auto brightness does not work

### ISSUE THREAD

**Issue by azuwis** [Jovian-Experiments/Jovian-NixOS#271]
Steps to reproduce auto brightness issue:

1. Ensure auto brightness is enabled in settings
2. At night, turn off all lights
3. Set brightness to min in quick settings
4. Turn on lights
5. The brightness slider won't move, and screen brightness won't automatically change in Jovian-NixOS.

<del>
Steps to reproduce screen brightness max issue:

1. At night, turn off all lights
2. Set brightness to min in quick settings
3. Press power button to suspend
4. Press power button to resume
5. The brightness slider won't move, but the screen brightness will set to max, and burn your eyes :(
</del>

Edit: The screen brightness max issue no longer exists on current HEAD commit https://github.com/Jovian-Experiments/Jovian-NixOS/commit/fd13986ede9b94c50e84aecb2c88863e297bbb52

Compare to SteamOS closely, SteamOS does not have those issues.

User that run Steam:

```
$ id
uid=1000(deck) gid=1000(deck) groups=1000(deck),1(wheel),100(users)
```

[Setup](https://github.com/azuwis/nix-config/blob/master/hosts/steamdeck.nix), not sure if it's an OLED specific issue.

**Comment by samueldr** [comment]
(Sorry it took a while to get back with a reply.)

I've confirmed the issue on both of my LCD and OLED model.

I've checked that at the very least the device is showing-up and working as intended with:

```
 $ watch -n0.2 'grep . /sys/bus/iio/devices/iio*/in_illuminance_*'
```

And application of photons from a flashlight.

* * *

One thing I'm not sure of, but I am now assuming from your report: On SteamOS, enabling this option makes the actual brightness slider change, is that it?

Though I could at least observe that I couldn't observe what was on the display with the bright light on.

**Comment by azuwis** [comment]
> One thing I'm not sure of, but I am now assuming from your report: On SteamOS, enabling this option makes the actual brightness slider change, is that it?

On SteamOS, the brightness slider in the quick access menu will be automatically moved left and right according to the current illuminance, and the actual screen brightness will also be automatically adjusted up and down.

**Comment by samueldr** [comment]
Thank you for the reply. This is helping confirm some assumptions I had.
