### ISSUE TITLE
Steam Deck OLED gamescope-session crash when launching HDR games

### ISSUE THREAD

**Issue by jpgrego** [Jovian-Experiments/Jovian-NixOS#296]
I seem to be having issues executing games with HDR on my Steam Deck OLED. Upon attempting, gamescope-session seems to crash.
Launching the same games without HDR works perfectly.
I'm unsure when this started but I played HDR games back in January with no issues at all.

I'm attaching part of the gamescope log. Two details stand out:

1. `drmModeAtomicCommit: Permission denied` spammed multiple times
2. ```gamescope: ../src/backend.h:268: const T& gamescope::BackendBlob::View() const [with T = hdr_metadata_infoframe]: Assertion `sizeof( T ) == m_Data.size()' failed.```, followed by a core dump.

I've already tried:

1. Using Steam Beta version
2. Using Proton Experimental
3. Deleting the mura folder (`~/.config/gamescope/mura`) and using `galileo-mura-setup` again.
4. Replacing the mura folder with the contents of the `blob.tar` I obtained when I first installed Jovian back in December using `galileo-mura-extractor`. It didn't crash the gamescope-session with this but was stuck in the Steam game launching screen nevertheless.

Any tips on what might have gone wrong?

EDIT: added (quite messy) configuration.nix (with txt extension, since GitHub dislikes text files with exotic extensions I guess)

[gamescope.log](https://github.com/Jovian-Experiments/Jovian-NixOS/files/14426710/gamescope.log)
[configuration.txt](https://github.com/Jovian-Experiments/Jovian-NixOS/files/14433311/configuration.txt)

**Comment by K900** [comment]
Do you maybe have some overlays for the gamescope package? Or libdrm? Or libdisplay-info?

**Comment by jpgrego** [comment]
I don't think so, at least not intentionally. I added moonlight and chiaki, overriding buildInputs to include libplacebo and vulkan-headers (necessary to enable HDR). I tried to uninstall those, garbage collect and reboot for good measure, but problem remains.

I have attached my configuration.nix, for reference. Excuse the mess, I still didn't take the time to properly organize it and look into things like Nix flakes.

**Comment by K900** [comment]
Maybe you just need to reboot your system?

**Comment by jpgrego** [comment]
The good old "have you tried turning off and turning on again?" That's the first thing I tried. Multiple times already.

Or do you mean rebuilding NixOS with my config?

**Comment by K900** [comment]
I'd try rebuilding your NixOS against latest nixos-unstable before you do anything else.

**Comment by jpgrego** [comment]
Yeah, I think I'll try to do that ASAP. Thanks for your input!

**Comment by K900** [comment]
https://github.com/ValveSoftware/gamescope/commit/14a1db3a57612e5cfbba6d4c19688eafdc6c4043

lul

**Comment by jpgrego** [comment]
Oh, nice finding! Thank you! I'm going to update and test it :)

**Comment by jpgrego** [comment]
Yup, problem solved. Thanks again @K900 !
