### ISSUE TITLE
Expose a equivalent `programs.steam.extraCompatPackages` to steam

### ISSUE THREAD

**Issue by anthr76** [Jovian-Experiments/Jovian-NixOS#304]
With this [PR](https://github.com/NixOS/nixpkgs/pull/293564) addition it makes it very simple to add custom proton runtimes to steam with Nix.

Such as GE's fork of Proton. Perhaps we should add something similar here?

**Comment by K900** [comment]
Jovian's Steam already is just an override of normal Steam, so all the same override arguments still work.

**Comment by anthr76** [comment]
I have this,

```nix
  programs.steam.extraCompatPackages = [
    inputs.nixpkgs-pr-294532.legacyPackages.${pkgs.system}.proton-ge-custom
  ];
```


but it doesn't seem to take effect. I will double check if the environment variable is present.

**Comment by Atemu** [comment]
Note that that PR may simply not be creating a correct directory structure: https://github.com/NixOS/nixpkgs/pull/294532#discussion_r1523656697.

Anyhow, I don't think this issue should be tracked here as Jovian does not do anything special in this regard.

**Comment by VergeDX** [comment]
```nix
  jovian.steam.environment = {
    STEAM_EXTRA_COMPAT_TOOLS_PATHS =
      "${pkgs.proton-ge-bin.steamcompattool}";
  };
```

**Comment by Atemu** [comment]
Please use `programs.steam.extraCompatPackages = [ pkgs.proton-ge-bin ];`.
