### ISSUE TITLE
Sleep and more not working in gaming mode

### ISSUE THREAD

**Issue by fyredragon69** [Jovian-Experiments/Jovian-NixOS#309]
I've been using Jovian-NixOS for a few months now, and it's been.. interesting, to say the least
After wrapping my head around installing it (with some help from @ihaveamac ), I noticed some issues.

- Waking the Steam Deck from sleep results in a black screen
- Decky loader refuses to launch, no matter what
- Sound can randomly start and stop working
- Disconnecting a dock while in gaming mode results in the Steam Deck display being stuck on a black screen
I'm not sure how many of these issues are NixOS related or Jovian related, and I didn't see any issues mentioning them, so I figured I'd bring them up here.

**Comment by fyredragon69** [comment]
Update on this, it seems as of a few weeks ago the sleep and sound issue has been resolved, but Decky still does not work and I am still having dock issues.

**Comment by ChocolateLoverRaj** [comment]
@fyredragon69 if this issue is resolved then you should close it.

I am using Jovian on a normal desktop computer and sleep is working fine for me.
