### ISSUE TITLE
The option `services.xserver.displayManager.sessionPackages' does not exist

### ISSUE THREAD

**Issue by shelvacu** [Jovian-Experiments/Jovian-NixOS#318]
repro: https://gist.github.com/shelvacu/858d0a5fa65bf169d4942ffe369b05e9

Note this uses `nixos-unstable-small` rather than `nixos-unstable`, but it's just a matter of time.

**Comment by K900** [comment]
https://github.com/Jovian-Experiments/Jovian-NixOS/pull/317

**Comment by K900** [comment]
Fixed.
