### ISSUE TITLE
Warning generating install-iso using nixos generators after disabling network-manager

### ISSUE THREAD

**Issue by ParetoOptimalDev** [Jovian-Experiments/Jovian-NixOS#326]
I'm just trying to make an install-iso for my jovian-nixos steam deck configuration using nixos-generator modules. I ran into an issue at first:

https://github.com/nix-community/nixos-generators/issues/281

Then realized I could disable network manager to generate the iso and received error:

```
trace: warning: The Steam Deck UI integrates with NetworkManager (networking.networkmanager.enable) which is not enabled. NetworkManager is required to complete the first-time setup process.
```

I'm assuming it'll be fine and I can just re-enable/rebuild after, but wanted to bring the issue up here and link back to the nixos-generators issue in case anyone can think of some resolution to make this use case easier for others in the future.

**Comment by samueldr** [comment]
I don't know if there is anything that can be *done* here. I'm closing, but if there is something that can be handled on our end, please re-open and detail.

AFAIUI it's a fundamental difference in "opinion" around the network management model, ~~and yes `mkForce`'ing the option false (I suppose) for that other project may as well be the correction way to handle that~~ and it's a warning, it'll build.
