### ISSUE TITLE
Turning HDR on in display means games won't launch

### ISSUE THREAD

**Issue by Reilley64** [Jovian-Experiments/Jovian-NixOS#335]
I'm running Jovian on a PC with and AMD GPU. If I turn on HDR in the display settings any game I launch gets stuck on the steam loading spinner and won't launch. If I turn it off games will launch fine again but obviously without HDR.

**Comment by Reilley64** [comment]
Now getting this error when trying to launch with HDR enabled.

![20240427_213318.jpg](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/28533679/d18385cb-b3bf-4ab4-aabf-39c041808b38)

**Comment by euokyun** [comment]
I got similar issue on my OLED deck when I play games with FSR3 fg(game itself/mod). In my case Proton 9 (beta) solve the issue.

**Comment by Reilley64** [comment]
Unfortunately doesn't matter what proton version I'm using it still gives me that error whenever I have HDR turned on.

**Comment by Reilley64** [comment]
I think this is related to #338

**Comment by Reilley64** [comment]
Fixed with #339
