### ISSUE TITLE
Characters are displayed as boxes in some languages in Steam.

### ISSUE THREAD

**Issue by bigsaltyfishes** [Jovian-Experiments/Jovian-NixOS#355]
In some languages, like Japanese and Chinese, characters will be displayed as boxes in either Game Mode or Desktop Mode in Steam. As mentioned in the [ArchWiki](https://wiki.archlinux.org/title/Steam), Steam requires the `wqy_zenhei` package to display CJK characters. Additionally, I found that Steam is unable to find fonts correctly on NixOS. I followed the [NixOS Wiki](https://nixos.wiki/wiki/Fonts) to configure fonts for Flatpak in an attempt to solve this problem and discovered that Steam searches `$HOME/.local/share/fonts` to find fonts. I think it would be better to provide a systemd service to create a symbolic link to the current profile's fonts folder so that Steam can find fonts correctly.

![902a3f407a849f4f1a759d3d353a1cf](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/15278036/0b9dbbf7-ffac-4e89-a805-a4e44eb35b54)

```Nix
  i18n.fonts.fontDir.enable = true;
  systemd.user.services.link-fonts = {
    description = "Create symbolic link for fonts";
    wantedBy = [ "default.target" "graphical-session.target" ];
    before = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStartPre = ''
        ${pkgs.bash}/bin/bash -c "${pkgs.coreutils}/bin/test ! -e %h/.local/share && ${pkgs.coreutils}/bin/mkdir -p %h/.local/share || ${pkgs.coreutils}/bin/true"
      '';
      ExecStart = ''
        ${pkgs.bash}/bin/bash -c "${pkgs.coreutils}/bin/test ! -e %h/.local/share/fonts && ${pkgs.coreutils}/bin/ln -s /run/current-system/sw/share/X11/fonts %h/.local/share/fonts || ${pkgs.coreutils}/bin/true"
      '';
    };
  };
```

**Comment by K900** [comment]
We have a better (?) fix for CJK fonts in Steam in the works upstream: https://github.com/NixOS/nixpkgs/pull/312268

**Comment by euokyun** [comment]
I'm Korean and use Korean language. not tested J, C.

nixpkgs's fonts has missing font files that required to show cjk font on steam.

https://gist.github.com/euokyun/afa76e401e6b81312ca0bcaf72a67032
https://gist.github.com/euokyun/ca97575780a066202129a56c35600670
https://gist.github.com/euokyun/385dfab1aeec8dd70a0c5855cfed7e31

``` nix
	fonts = {
		packages = with pkgs; [
			(callPackage ./packages/adobe-source-code-pro-vf.nix {})
			(callPackage ./packages/noto-fonts-cjk-serif-without-vf.nix {})
			(callPackage ./packages/noto-fonts-cjk-sans-without-vf.nix {})
		];
		fontDir.enable = true;
		fontconfig.enable = true;
	};

	system.userActivationScripts.linktosharedfolder.text = ''
		if [[ ! -h "$HOME/.local/share/fonts" ]]; then
		 ln -s "/run/current-system/sw/share/X11/fonts" "$HOME/.local/share/fonts"
		fi
	'';

```

seems like steam only read fonts from $HOME/.local/share/fonts. so I link system font folder.

**Comment by Cryolitia** [comment]
> As mentioned in the [ArchWiki](https://wiki.archlinux.org/title/Steam), Steam requires the wqy_zenhei package to display CJK characters.

That's wrong, I have asked Arch to fix it. It's 2024 now, just let Wenquanyi stay peacefully in the museum.

> nixpkgs's fonts has missing font files that required to show cjk font on steam.

Unfortunately, we have yet to find a font that satisfies all East Asian users while not being too bulky to displease users in the Latin world. So I'm afraid we'll need some more sophisticated solution than providing a fixed font.

> seems like steam only read fonts from $HOME/.local/share/fonts. so I link system font folder.

Also `/usr/share/fonts`
