### ISSUE TITLE
No timestamp on kernel

### ISSUE THREAD

**Issue by vancluever** [Jovian-Experiments/Jovian-NixOS#359]
Just noticed there's no timestamp on the built kernel:

```
uname -a
Linux deck 6.5.0-valve7 #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux
```

Did a bit of digging and I'm guessing it's due to an inability for the build process to currently properly derive `SOURCE_DATE_EPOCH`, which is the source of `KBUILD_BUILD_TIMESTAMP`.

Did a little bit more digging and found https://github.com/NixOS/nixpkgs/pull/256270#issue-1904395781, which looks like it might be the issue, given that the custom kernel is fetched with `fetchFromGitHub`. Incidentally, it looks like there's been recent activity on it (hopefully close to being merged), so maybe it could be helpful here in solving this once it's live.

**Comment by K900** [comment]
This is a feature, not a bug.

**Comment by samueldr** [comment]
> This is a feature, not a bug.

There *could* be a timestamp, the one from the sources, but this is not our bug.

See the linked PR:

> Currently, set-source-date-epoch-to-latest.sh only correctly populates the `SOURCE_DATE_EPOCH` environment variable for archives that are unpacked during the derivation unpack phase.

But then, not our bug, and will/would be solved upstream for everything all at once.

**Comment by vancluever** [comment]
> But then, not our bug, and will/would be solved upstream for everything all at once.

Unless my read on the PR is wrong, I think `keepSourceDate` will need to be explicitly added in `pkgs/linux-jovian/default.nix`.

In any case, yeah, not a huge deal, and I understand it's not a bug due to anything here. It's just more of an aesthetic nit, it would be nice to see the source date on the kernel just in case someone hasn't necessarily been following along just based on version tag alone.
