### ISSUE TITLE
jovian-greeter-wrapped -- pam_acct_mgmt : PERM_DENIED error on boot

### ISSUE THREAD

**Issue by Celleforst** [Jovian-Experiments/Jovian-NixOS#375]
I am trying to install nixos on my steamdeck with a very basic configuration that is based on this old tutorial: https://heywoodlh.io/nixos-steamdeck. 
However, when I boot I get the error "pam_acct_mgmt : PERM_DENIED" from jovian-greeter-wrapped in boot stage 2. The steam menu does not appear.

Here is my configuration.nix:
````
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ./steam-deck.nix
    ];

  boot.loader = {
    efi = {
      canTouchEfiVariables = true;
    };
    grub = {
      enable = true;
      #useOSProber = true;
      device = "nodev";
      efiSupport = true;
    };
  };

  networking.hostName = "nix-steam-deck"; # Define your hostname.

  # Set your time zone.
  time.timeZone = "Europe/Zurich";

  system.stateVersion = "24.05";

}
````

And steam-deck.nix:

````
{ config, pkgs, lib, ... }:

let
  myUsername = "mk";

  # Fetch the "development" branch of the Jovian-NixOS repository
  jovian-nixos = builtins.fetchGit {
    url = "https://github.com/Jovian-Experiments/Jovian-NixOS";
    ref = "development";
  };

in {
  # Import jovian modules
  imports = [ "${jovian-nixos}/modules" ];

  networking.networkmanager.enable = true;
  # Enable GNOME
  sound.enable = true;
  services.desktopManager.plasma6 = {
    enable = true;
  };

  # Create user
  users.users.myUsername = {
    isNormalUser = true;
    extraGroups = ["wheel"];
  };

  jovian = {
    steam = {
	enable = true;
	autoStart = true;
	desktopSession = "plasma";
	user = myUsername;
    };
    devices.steamdeck = {
      enable = true;
    };
  };

  environment.systemPackages = with pkgs; [
    gnome.gnome-terminal
  ];
}
````

Does anyone know why I might be getting this error? Is there something wrong with my config? 
Besides that, does anyone have some working nixos configs for steamdeck? I am having difficulties setting mine up and an example config would be of great help.

**Comment by K900** [comment]
Post the full log please.

**Comment by K900** [comment]
Actually, I'm pretty sure the problem is that you're defining `users.users.myUsername`, which creates a user literally named `myUsername`. You want `users.users.${myUsername}`.

**Comment by Celleforst** [comment]
Thanks for the quick reply. Oh wow sorry, yeah that fixed it, thanks :)

**Comment by Celleforst** [comment]
Thanks for the quick reply. Oh wow sorry, yeah that fixed it, thanks :)
