### ISSUE TITLE
Decky Loader SHA256 mismatch

### ISSUE THREAD

**Issue by LAlto96** [Jovian-Experiments/Jovian-NixOS#385]
Hi guys !

Just here to report an SHA256 mismatch when trying to enable Decky Loader :

![image](https://github.com/Jovian-Experiments/Jovian-NixOS/assets/112064171/27edaf3d-93ca-476a-9db0-4697fe9c2ac0)

**Comment by euokyun** [comment]
I think this is same issue #262 , and #380 will merge soon I think.
and that works for me.

**Comment by K900** [comment]
Fixed, please update.
