### ISSUE TITLE
Can you upstream this project ?

### ISSUE THREAD

**Issue by liberodark** [Jovian-Experiments/Jovian-NixOS#431]
Hi,

Do you think it will be possible to upload your packages directly to nixos rather than going through a repository ?
You have a lot of packages and kernels/options that could be upstreamed directly to nixos and thus simplify their use.

Best Regards

**Comment by K900** [comment]
No, vendor kernels are not supposed to go into nixpkgs, and many other packages here are technically legally questionable.
