### ISSUE TITLE
Bluetooth breakage on Steam Deck (Bluez 5.78 regression?)

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#441]
[This is a tracking issue...]

* * *

Observed on this system, but likely not specifically exact:

  - On Kernel `6.8.12-valve3`
  - With Nixpkgs `nixos-24.11pre696981.18536bf04cd7`

Things known:

  - `bluetoothd` with Bluez 5.78, and 5.79, uses 100% CPU usage.
  - Steam will take *some time* to start after the updater applet ran. ("Stuck on the SteamOS logo...")
  - Bluez 5.76 and 5.77 on the same system does not exhibit the issue.
  - The SteamOS vendor config for Bluetooth does not affect this behaviour.
  - The same config and pins, but with mainline `6.11.5` on GPD Win Mini doesn't exhibit this issue.

Things to check:

 - With kernel 6.5-valveXX

 - With mainline on Steam Deck

* * *

Reportedly *Bluez 5.79* has the same issue (devusb in the Matrix room). **confirmed**

**Comment by devusb** [comment]
I ran a bisect on Bluez -- [this commit](https://github.com/bluez/bluez/commit/9cc587947b6ac56a4c94dcc880b273bc72af22a8) seems to be the first bad one.

**Comment by samueldr** [comment]
Here's what `strace` sees it's doing in a loop:

```
115228 poll([{fd=3<{eventfd-count=0x3, eventfd-id=3, eventfd-semaphore=0}>, events=POLLIN}, {fd=7<UNIX-STREAM:[280298->290022]>, events=POLLIN}, {fd=8<socket:[288901]>, events=POLLIN}, {fd=9<socket:[288902]>, events=POLLIN}, {fd=10</proc/sys/kernel/hostname>, events=0}, {fd=12<NETLINK:[KOBJECT_UEVENT:115228]>, events=POLLIN}, {fd=13</dev/rfkill<char 10:242>>, events=POLLIN}, {fd=14<signalfd:[INT USR2 TERM CHLD]>, events=POLLIN}, {fd=18<socket:[288908]>, events=POLLIN}, {fd=19<socket:[288909]>, events=POLLIN}, {fd=20<socket:[288910]>, events=POLLIN}, {fd=21<socket:[288911]>, events=POLLIN}, {fd=22<socket:[288912]>, events=POLLIN}, {fd=23<socket:[288913]>, events=POLLIN}, {fd=24<socket:[288914]>, events=POLLIN}, {fd=25</dev/uhid<char 10:239>>, events=POLLIN}, {fd=26</dev/uhid<char 10:239>>, events=POLLIN}, {fd=27</dev/uhid<char 10:239>>, events=POLLIN}, {fd=28<socket:[277428]>, events=POLLIN}, {fd=29<socket:[277429]>, events=POLLIN}], 20, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=8, revents=POLLIN}])
115228 read(3<{eventfd-count=0x3, eventfd-id=3, eventfd-semaphore=0}>, "\3\0\0\0\0\0\0\0", 8) = 8
115228 write(3<{eventfd-count=0, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 read(8<socket:[288901]>, "*\0\0\0\17\0;n\246]\2104\0\1\0\0\0\1\0\0\0", 512) = 21
115228 write(3<{eventfd-count=0x1, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 poll([{fd=3<{eventfd-count=0x2, eventfd-id=3, eventfd-semaphore=0}>, events=POLLIN}, {fd=7<UNIX-STREAM:[280298->290022]>, events=POLLIN}, {fd=8<socket:[288901]>, events=POLLIN}, {fd=9<socket:[288902]>, events=POLLIN}, {fd=10</proc/sys/kernel/hostname>, events=0}, {fd=12<NETLINK:[KOBJECT_UEVENT:115228]>, events=POLLIN}, {fd=13</dev/rfkill<char 10:242>>, events=POLLIN}, {fd=14<signalfd:[INT USR2 TERM CHLD]>, events=POLLIN}, {fd=18<socket:[288908]>, events=POLLIN}, {fd=19<socket:[288909]>, events=POLLIN}, {fd=20<socket:[288910]>, events=POLLIN}, {fd=21<socket:[288911]>, events=POLLIN}, {fd=22<socket:[288912]>, events=POLLIN}, {fd=23<socket:[288913]>, events=POLLIN}, {fd=24<socket:[288914]>, events=POLLIN}, {fd=25</dev/uhid<char 10:239>>, events=POLLIN}, {fd=26</dev/uhid<char 10:239>>, events=POLLIN}, {fd=27</dev/uhid<char 10:239>>, events=POLLIN}, {fd=28<socket:[277428]>, events=POLLIN}, {fd=29<socket:[277429]>, events=POLLIN}], 20, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=8, revents=POLLIN}])
115228 read(3<{eventfd-count=0x2, eventfd-id=3, eventfd-semaphore=0}>, "\2\0\0\0\0\0\0\0", 8) = 8
115228 write(3<{eventfd-count=0, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 read(8<socket:[288901]>, "\1\0\0\0\n\0P\0\0;n\246]\2104\0", 512) = 16
115228 write(3<{eventfd-count=0x1, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 write(3<{eventfd-count=0x2, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 poll([{fd=3<{eventfd-count=0x3, eventfd-id=3, eventfd-semaphore=0}>, events=POLLIN}, {fd=7<UNIX-STREAM:[280298->290022]>, events=POLLIN}, {fd=8<socket:[288901]>, events=POLLIN|POLLOUT}, {fd=9<socket:[288902]>, events=POLLIN}, {fd=10</proc/sys/kernel/hostname>, events=0}, {fd=12<NETLINK:[KOBJECT_UEVENT:115228]>, events=POLLIN}, {fd=13</dev/rfkill<char 10:242>>, events=POLLIN}, {fd=14<signalfd:[INT USR2 TERM CHLD]>, events=POLLIN}, {fd=18<socket:[288908]>, events=POLLIN}, {fd=19<socket:[288909]>, events=POLLIN}, {fd=20<socket:[288910]>, events=POLLIN}, {fd=21<socket:[288911]>, events=POLLIN}, {fd=22<socket:[288912]>, events=POLLIN}, {fd=23<socket:[288913]>, events=POLLIN}, {fd=24<socket:[288914]>, events=POLLIN}, {fd=25</dev/uhid<char 10:239>>, events=POLLIN}, {fd=26</dev/uhid<char 10:239>>, events=POLLIN}, {fd=27</dev/uhid<char 10:239>>, events=POLLIN}, {fd=28<socket:[277428]>, events=POLLIN}, {fd=29<socket:[277429]>, events=POLLIN}], 20, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=8, revents=POLLOUT}])
115228 read(3<{eventfd-count=0x3, eventfd-id=3, eventfd-semaphore=0}>, "\3\0\0\0\0\0\0\0", 8) = 8
115228 write(3<{eventfd-count=0, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 writev(8<socket:[288901]>, [{iov_base="P\0\0\0\v\0\356\r\261\306\265d\0\1\0\0\0", iov_len=17}], 1) = 17
115228 write(3<{eventfd-count=0x1, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
115228 write(3<{eventfd-count=0x2, eventfd-id=3, eventfd-semaphore=0}>, "\1\0\0\0\0\0\0\0", 8) = 8
```

**Comment by devusb** [comment]
if I run `btmgmt` my console is flooded with
```
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: C5:84:D5:14:F2:DA (LE Random)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
[mgmt]# hci0 device_flags_changed: 15:05:00:10:05:03 (BR/EDR)
[mgmt]#      supp: 0x00000003  curr: 0x00000003
```

**Comment by samueldr** [comment]
"Same", but different, required `sudo` to see those.

Looping in set of threes, just like the `strace`'d thing.

```
[mgmt]# hci0 device_flags_changed: 34:88:5D:A6:6E:3B (BR/EDR)
[mgmt]#      supp: 0x00000001  curr: 0x00000001
[mgmt]# hci0 device_flags_changed: 64:B5:C6:B1:0D:EE (BR/EDR)
[mgmt]#      supp: 0x00000001  curr: 0x00000001
[mgmt]# hci0 device_flags_changed: 00:1B:FB:BE:53:E7 (BR/EDR)
[mgmt]#      supp: 0x00000001  curr: 0x00000001
```

The exact flags here (observed on an LCD model Steam Deck, Bluez 5.79) differ, but that's unlikely to matter I guess?

~~Main thing I can think of is I'm not sure I have any device paired with that system.~~

* * *

I just checked, I have some

```
[bluetooth]# devices 
Device 00:1B:FB:BE:53:E7 Sony PLAYSTATION(R)3 Controller
Device E8:AB:FA:29:C3:24 TAOTRONICS
Device 64:B5:C6:B1:0D:EE Pro Controller
Device 34:88:5D:A6:6E:3B Keyboard K480
```

And other than the TAOTRONICS bluetooth headset, they are represented in that spew :thinking:.

**Comment by devusb** [comment]
Mine was from an OLED currently on Bluez `9cc587947b6ac56a4c94dcc880b273bc72af22a8` (haven't rebooted yet) -- also have a few devices paired.

**Comment by samueldr** [comment]
[Just saying, with the OLED model you can't check against mainline in a reliable manner...]

Just tested with

```diff
+  specialisation = {
+    "With mainline Linux" = {
+      configuration = {
+        boot.kernelPackages = lib.mkForce pkgs.linuxPackages_latest;
+      };
+    };
+  };
```

And I no issue there. So the issue stems more likely from one of:

 - from vendor changes
 - older kernel semantics

By vendor changes, I also want to imply it could be caused by not having a bugfix forwardported or backported yet.

* * *

And mainline `6.6.58` is okay too.

**Comment by samueldr** [comment]
Putting my guessing hat on:

 - ***sus*** https://github.com/Jovian-Experiments/linux/commit/3ea1541efc91116181ec4abcebd62810df7aff33

Or really, possibly the whole change set?

 - [7a4b4416fa119f3ff4fb48d77eb1ffa83c910730^1..3ea1541efc91116181ec4abcebd62810df7aff33](https://github.com/Jovian-Experiments/linux/compare/7a4b4416fa119f3ff4fb48d77eb1ffa83c910730%5E1...3ea1541efc91116181ec4abcebd62810df7aff33)

NOTE: As I said *guessing hat on*, I haven't done any leg work yet to confirm this theory.

Additional NOTE: AFAIUI this is yes for the OLED model hardware support. So removing these changes only serves as a way to identify where the regression may come from.

**Additional additional NOTE: Reverting those changes makes bluetoothd behave**.

* * *

Observations

 - OK
     - [926743c6c2cc4ec07d549b46914e02b5e0a4276d](https://github.com/Jovian-Experiments/linux/commit/926743c6c2cc4ec07d549b46914e02b5e0a4276d) can be dropped, since [a7f8dedb4be2cc930a29af24427b885405ecd15d](https://github.com/Jovian-Experiments/linux/commit/a7f8dedb4be2cc930a29af24427b885405ecd15d) is the origin commit AFAICT of what was previously a forward port.
     - [59ae0669c1f1cf4136aa7df9bb5589b90972f728](https://github.com/Jovian-Experiments/linux/commit/59ae0669c1f1cf4136aa7df9bb5589b90972f728) is in mainline 6.11, so presumed okay
 - TBD
     - [44b856dfa3f3eab4df323fecc8887fb52f2430e5](https://github.com/Jovian-Experiments/linux/commit/44b856dfa3f3eab4df323fecc8887fb52f2430e5) might have an upstream-related fix to consider
         - https://lore.kernel.org/all/20240107180252.73436-1-verdre@v0yd.nl/

~~Left to reason about;~~ (unneeded.)

 - ~~[7a4b4416fa119f3ff4fb48d77eb1ffa83c910730](https://github.com/Jovian-Experiments/linux/commit/7a4b4416fa119f3ff4fb48d77eb1ffa83c910730)~~
 - ~~[ff422d3553d420bc0924305ea52a0f46ed36fb12](https://github.com/Jovian-Experiments/linux/commit/ff422d3553d420bc0924305ea52a0f46ed36fb12)~~
 - ~~[3ea1541efc91116181ec4abcebd62810df7aff33](https://github.com/Jovian-Experiments/linux/commit/3ea1541efc91116181ec4abcebd62810df7aff33)~~

**Comment by samueldr** [comment]
So, just looking at the patches and trying to intuit it... I think that

 - https://github.com/Jovian-Experiments/linux/commit/3ea1541efc91116181ec4abcebd62810df7aff33

was meant to work around the issue or solve the issue that

 - https://github.com/bluez/bluez/commit/9cc587947b6ac56a4c94dcc880b273bc72af22a8

has solved?

It's hard to tell without knowing more about the intent behind the Quectel-authored change here.

* * *

So I asked myself: *what's the deal with `sk`?*

And followed the breadcrumbs back to:

 - https://github.com/Jovian-Experiments/linux/blob/b9bc2d44db5b6ea54333d20a02de16780e41acb9/net/bluetooth/mgmt_util.c#L111-L112

and then

 - https://github.com/Jovian-Experiments/linux/blob/b9bc2d44db5b6ea54333d20a02de16780e41acb9/net/bluetooth/hci_sock.c#L349-L350

to land on:

 - https://github.com/Jovian-Experiments/linux/blob/b9bc2d44db5b6ea54333d20a02de16780e41acb9/net/bluetooth/hci_sock.c#L329-L331

So uuuuuuuuuuuuuuuuuuh... The change seems to make it so the flag change events cause an "unexpected echo", and hearing back about its own changes... and **luckily enough** the bluez-side expectations are documented:

>  Afterwards, it is only sent to mgmt sockets other than the one which called `set_device_flags`.

 - https://github.com/bluez/bluez/blob/9cc587947b6ac56a4c94dcc880b273bc72af22a8/src/device.c#L7264-L7265

So this change is entirely 100% wrong as far as base expectations from bluez go.

* * *

Now, *something* smells *off* in the bluez-side change set too...

Reading the commit message:

> In order to do this properly the code needs to track the pending_flags
> being set **and also call btd_device_flags_changed whenever a change is
> complete since that event is not generated when MGMT_OP_SET_DEVICE_FLAGS
> is sent by bluetoothd itself.**

(Emphasis my own.)

So I guess now the message is being received once from the kernel changes, and then also from itself sending it down the pipe... :thinking: 

Though I wonder if there is some defensive programming that could have helped on the bluez-side of things. E.g. not broadcasting a change event for no-ops? But I don't know their model to know if it would be correct or not.

* * *

**What is known is that the Quectel-authored change is incorrect as far as bluez needs.**


* * *

Oh, I should learn to read.

> 2) Resolved an issue where bluez lib could not receive
>   `MGMT_EV_DEVICE_FLAGS_CHANGED` notifications after sending
>   `MGMT_OP_SET_DEVICE_FLAGS`

The intent from the kernel-side patch ***is*** to make bluez self-aware. :thinking: 

Doubly-so this is not needed anymore.
