### ISSUE TITLE
zenpower instead of k10temp

### ISSUE THREAD

**Issue by appsforartists** [Jovian-Experiments/Jovian-NixOS#451]
When I was setting up my Legion Go, I read that `k10temp` is deprecated and that AMD APUs should instead use `zenpower`.  It's supposed to give more accurate readings on modern APUs.  Thus, this stanza in my configuration:

```nix
    extraModulePackages = with config.boot.kernelPackages; [zenpower];
    kernelModules = ["zenpower"];
    blacklistedKernelModules = ["k10temp"];
```

Now that Jovian has a `devices` package, I'm hoping to upstream the useful bits of my setup to help others (#450).  That has me wondering if I should port this over to `jovian.hardware.has.amd.gpu`, perhaps as `jovian.hardware.amd.gpu.enableZenpower` or `jovian.hardware.amd.gpu.enableMoreAccurateThermalReadings`.

**Comment by appsforartists** [comment]
Related: #305 by @Krutonium

**Comment by K900** [comment]
No idea where you got that from, k10temp is very much supported upstream.
