### ISSUE TITLE
Steamdeck not waking from sleep

### ISSUE THREAD

**Issue by charludo** [Jovian-Experiments/Jovian-NixOS#456]
Hi,

this project has been a pleasure to install and set up. However, I am currently experiencing one issue which makes into super annoying to use the deck, and that is that the deck will not wake from sleep mode. It will go into sleep mode just fine, but then not react at all to pressing the power button again. (No sound / controls / back light / ...).

While not my video, and not Jovian-NixOS related, I have found a single video online with the exact same symptoms: https://www.youtube.com/watch?v=7Kxrk9f6izI

Interestingly, the same thing also happens when entering sleep mode from the desktop-mode (plasma6).

Would appreciate some help/pointers :)

**Comment by K900** [comment]
This looks like a regression with the latest kernel. I'll revert it tomorrow, unless there's a fix upstream.

**Comment by charludo** [comment]
> This looks like a regression with the latest kernel. I'll revert it tomorrow, unless there's a fix upstream.

Oof that response was so instant, it scared me! 😂 

But awesome, thank you :D

**Comment by K900** [comment]
Reverted.
