### ISSUE TITLE
Flake support?

### ISSUE THREAD

**Issue by LEXUGE** [Jovian-Experiments/Jovian-NixOS#61]
I wish we could have more idiomatic support for flake here.

**Comment by TheOPtimal** [comment]
Yeah, plus it would also ease the need for things like nixpkgs pinning which is done in this repository.

**Comment by m1cr0man** [comment]
I've ended up building a flake for this repo in my fork, but I'm trying to work out now how to convert the CI steps that rely on non-flake configuration into something flake compatible. Specifically, working around nix-build-uncached having no flake equivalent.

**Comment by wkral** [comment]
Looks like this is solved with #117 which introduced a `flake.nix` file.

**Comment by samueldr** [comment]
Let's assume so, if there's an issue using it, please open a new issue :).
