### ISSUE TITLE
steam-session issues with GDM [NVIDIA]

### ISSUE THREAD

**Issue by from-nibly** [Jovian-Experiments/Jovian-NixOS#63]
I have gdm and gnome as part of my desktop environment on a machine i'm trying to install on this. When I enable `jovian.steam.enable` I don't get an additional option to login to the steam-session session. I've tried setting `services.xserver.displayManager.gdm.wayland` set to true. Is there a specific desktop manager that this works with?

**Comment by from-nibly** [comment]
Ok it actually looks like this is some gdm x wayland x nvidia issue.

**Comment by samueldr** [comment]
Note that testing against non-steamdeck has been minimal (close to zero). Your mileage **will** vary.

Not that this is undesirable to want to support, but that we will need any help :).

**Comment by from-nibly** [comment]
Yeah I think this has more to do with my computers support with nvidia and wayland than it has to do with this specific repo.

Do you know if the steam deck gui works under x11? If so maybe it would be worth looking into an x11 variant of the steam-session script. :shrug:

**Comment by zhaofengli** [comment]
You can use gamescope in nested mode from an existing X11 or Wayland desktop (just run `steam-session`), albeit with increased latency.

**Comment by K900** [comment]
Is this still an issue?

**Comment by from-nibly** [comment]
It's not a problem for me anymore. You can close this if you like.
