### ISSUE TITLE
ISO with no installer created by `nix-build -A isoPlasma`?

### ISSUE THREAD

**Issue by deftdawg** [Jovian-Experiments/Jovian-NixOS#66]
Hi, I'm a nixOS noob running it on my desktop for the first time.   I'd like to eventually get the system to work with steam big picture and gamescope.

To investigate how close Jovian gets me to my goal, I checked out the repo and built the ISO with `nix-build -A isoPlasma` and booted on a Virtualbox , unfortunately it appears as though the KDE plasma5 installer is not actually included with the ISO.

![image](https://user-images.githubusercontent.com/4991612/216833763-7eec8e2a-0712-46db-9751-2112293f2346.png)

Not sure if I missed something or where to go from here.

**Comment by zhaofengli** [comment]
The GUI-based installer isn't included in the image, and you will need to follow the steps in the [Manual Install](https://nixos.org/manual/nixos/unstable/index.html#sec-installation-manual) section of the manual. The problem is that the GUI installation flow only configures the base NixOS and doesn't add in the Jovian bits in this repo.

If you still want to try it out, you can make [this line](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/212c8e630b7267a5a712b3b20e4403cf232fd9e0/default.nix#L36) import `installation-cd-graphical-calamares-plasma5.nix` instead and rebuild the image. After installing with the Calamares-based installer, you will need to configure the Jovian bits yourself.

It would be nice to look into integrating with the GUI installer in the future.

**Comment by samueldr** [comment]
(The attributes were added before the installer was added to NixOS, I think.)

**Comment by deftdawg** [comment]
Oh, I get it now...  this is a nixOS system that has the valve 5.13 kernel to support SteamDeck's hardware.

Looking through the module files, I'm guessing I may only want to grab `/modules/steam.nix` which looks to setup steam, mangohud and display-manager on a system that is already up and running.

> If you still want to try it out, you can make [this line](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/212c8e630b7267a5a712b3b20e4403cf232fd9e0/default.nix#L36) import `installation-cd-graphical-calamares-plasma5.nix` instead and rebuild the image. After installing with the Calamares-based installer, you will need to configure the Jovian bits yourself.

Feel like that approach would be faster than manually configuring everything and partitioning.

**Comment by zhaofengli** [comment]
> Looking through the module files, I'm guessing I may only want to grab `/modules/steam.nix` which looks to setup steam, mangohud and display-manager on a system that is already up and running.

We overlay a few things (like `steam` and `mangohud`) so you should just import `modules/default.nix`. Apart from the overlay, the modules are inert unless you explicitly enable them in your configuration.

**Comment by deftdawg** [comment]
I did the following:
```sh
mkdir ~/source
cd ~/source
git clone https://github.com/Jovian-Experiments/Jovian-NixOS
sudo nano /etc/nixos/configuration.nix
# add `home/deftdawg/source/Jovian-NixOS/modules/default.nix` to `imports`
# add ` jovian.steam.enable = true;`
sudo nixos-rebuild switch
```

`steam-session` got created and I can run that from within my X11 session,  it defaults to 1280x800 resolution, but can be forced into 1080p by using `export GAMESCOPE_WIDTH=1920 GAMESCOPE_HEIGHT=1200`.   Any resolution above that and `gamescope` crashes at `Verifying Installation...` (`kill -9 $(ps -ef | grep -v grep | grep gamescope | cut -b10-18` to get out of it).   This is nested X11 rather than standalone, so I don't think mangohud will work(?), not sure though and performance won't be as good as what the deck does when it relaunches...  

I noticed there's `Gaming Mode` short cut that is supposed to get created for `Wayland`, unfortunately my session is the installation default `X11`.   I had a look at my stock steamdeck and it's also running `X11`. 

Anyway I'm not sure where I'm going with this... just random ramblings.  :laughing:

**Comment by zhaofengli** [comment]
> steam-session got created and I can run that from within my X11 session, it defaults to 1280x800 resolution, but can be forced into 1080p by using export GAMESCOPE_WIDTH=1920 GAMESCOPE_HEIGHT=1200. Any resolution above that and gamescope crashes at Verifying Installation... (kill -9 $(ps -ef | grep -v grep | grep gamescope | cut -b10-18 to get out of it).

Hmm, setting a higher resolution works for me on my Framework Laptop. We need to look at what went wrong here.

> This is nested X11 rather than standalone, so I don't think mangohud will work(?), not sure though and performance won't be as good as what the deck does when it relaunches...

`mangohud` should work even when gamescope is running in nested mode. Did you try enabling the performance overlay? On the keyboard, the Steam button is `Ctrl-1` and the Quick Access Button is `Ctrl-2`.

> I noticed there's Gaming Mode short cut that is supposed to get created for Wayland, unfortunately my session is the installation default X11. I had a look at my stock steamdeck and it's also running X11.

Something may be preventing the display manager from running on Wayland. If I recall correctly GDM will not list Wayland sessions if it's running X11. You can try launching `steam-session` directly in a TTY. On a stock Steam Deck, the Plasma desktop is X11 and the Gaming Mode is Wayland with gamescope as the compositor [^1].

[^1]: But even though gamescope is a Wayland compositor, it only [officially supports](https://github.com/Plagman/gamescope/commit/98d61844d81f0ef39358c6336eed477054c4c320) X11 applications via Xwayland 😛

**Comment by deftdawg** [comment]
> Hmm, setting a higher resolution works for me on my Framework Laptop. We need to look at what went wrong here.

I added `wayland` to pkgs and messed around with trying add `GAMESCOPE_WIDTH`/`GAMESCOPE_HEIGHT` to  `jovian.steam.environment`... after a rebuild I noticed `Gaming Mode` appeared as a pick-able session in sddm.

I also noticed I could launch steam-session from a tty...  I can cause the  "Verifying Installation... " crash by going into `Display` and turn-off `automatic resolution`, and picking any refresh rate higher than `1920x1200@60` (i.e. 2K@30, 4k@60, etc) ...  When automatic res is turned off the chosen resolution gets written to `~/.config/gamescope/modes.cfg` (i.e.  `MSI MPG321UR-QD:1920x1200@60`)... 

I think it's something to do with gamescope (Plagman/gamescope#642) tbh, because it crashed exactly the same way on HoloISO.

It sucks because during the session, everything runs wonderfully at the higher resolution/refresh (at for the games I play a 6900XT is massive overkill).

> `mangohud` should work even when gamescope is running in nested mode. Did you try enabling the performance overlay? On the keyboard, the Steam button is `Ctrl-1` and the Quick Access Button is `Ctrl-2`.

I have no clue why mangohud doesn't work... Ctrl-1 and Ctrl-2 don't work at all for me, I tried a different keyboard, same deal.   I can see them running in `ps`, it's just weird.

I'm going to see if I can figure out how to debug gamescope...  at least it's fairly straightforward to build at least.   
```
 mkdir -p ~/source/gamescope
 cd ~/source/gamescope
 nix-build -E 'with import <nixpkgs> {}; enableDebugging gamescope'
```

Actually, getting a gdb session remotely attached to my laptop will probably be another story :laughing:

**Comment by deftdawg** [comment]
> I have no clue why mangohud doesn't work... Ctrl-1 and Ctrl-2 don't work at all for me, I tried a different keyboard, same deal. I can see them running in `ps`, it's just weird.

Running nested inside X11, I see this:
```
System startup time: 2.21 seconds
BuildCompleteAppOverviewChange: 266 apps
RegisterForAppOverview 1: 1ms
RegisterForAppOverview 2: 1ms
No cached sticky mapping in DeactivateActionSetLayer.The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
Errors from xkbcomp are not fatal to the X server
```
Which probably accounts for why they don't work under X, however from a tty running wayland(?), there's nothing in the console output like that.
