### ISSUE TITLE
Automatic dock update?

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#68]
We could make the dock updater work like on Steam OS by adding this path to the FHS:

 - `/usr/bin/steamos-polkit-helpers/jupiter-dock-updater`

From the logs:

```
Mar 04 15:53:02 dashdingo games-session-start[21574]: sh: line 1: /usr/bin/steamos-polkit-helpers/jupiter-dock-updater: No such file or directory                                                                                     
```

**Comment by sg-qwt** [comment]
How about the same stub approach as in [fhsenv](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/pkgs/steam-jupiter/fhsenv.nix) and ask user to run on demand instead?

**Comment by samueldr** [comment]
Yeah, this was more of a placeholder issue while I had the path in sight.

Still a big TBD, what we want to do with all the firmware-ish update things.

**Comment by samueldr** [comment]
cc  #87

**Comment by samueldr** [comment]
Closing since #87 encompasses this decision anyway...
