### ISSUE TITLE
Black screen upon second launch with custom resolution

### ISSUE THREAD

**Issue by ghost** [Jovian-Experiments/Jovian-NixOS#71]
Hi! 🙂 I'm using this config on my NixOS desktop PC. Thanks for your work!

The `Gaming Mode` session is working fine, except that the default resolution of `gamescope` doesn't match my ultra-wide monitor. I need to go to `Menu > Settings > Display` and disable `Automatically Set Resolution`. It then works fine until I log out of the session and launch it again. Upon subsequent launches, I can see the Steam Deck logo with `Verifying Installation...`, then I can hear the boot sound, but the screen remain frozen with the Deck logo.

My workaround is to set `GAMESCOPE_MODE_SAVE_FILE` to a temporary file, and to disable `Automatically Set Resolution` each time I launch the session:

``` diff
diff --git a/modules/steam.nix b/modules/steam.nix
index c0688ff..7b28ce7 100644
--- a/modules/steam.nix
+++ b/modules/steam.nix
@@ -134,10 +134,7 @@ let
     echo "1x1" > "$RADV_FORCE_VRS_CONFIG_FILE"
 
     # Prepare gamescope mode save file (3.1.44+)
-    gamescope_config_dir="''${XDG_CONFIG_HOME:-$HOME/.config}/gamescope"
-    mkdir -p "$gamescope_config_dir"
-    export GAMESCOPE_MODE_SAVE_FILE="$gamescope_config_dir/modes.cfg"
-    touch "$GAMESCOPE_MODE_SAVE_FILE"
+    export GAMESCOPE_MODE_SAVE_FILE=$(mktemp --tmpdir gamescope-mode.XXXXXXXX)
 
     gamescope_incantation=(
       "${gamescope-shim}"

```

**Comment by ghost** [comment]
I upgraded from 65b11d8 to 449faaa upon upgrading to **NixOS 23.05**, and this issue disappeared. I removed my patch. 🙃

**Comment by samueldr** [comment]
Thank you for coming back and telling us it stopped being broken!

**Comment by ghost** [comment]
No problem! 🙂
