### ISSUE TITLE
How to improve switch between game / desktop modes?

### ISSUE THREAD

**Issue by rapenne-s** [Jovian-Experiments/Jovian-NixOS#77]
Hi,

How could we make a smoother transition between desktop and gaming mode?

Right now, I've set up steam-wayland as the default session for the display manager, and set autologin, and allowed passwordLess login for my user, with this setup:

- system boots on steam pal mode
- steam switch to desktop leads me to lightdm (gdm is bad with passwordless as it doesn't allow you to choose the session...)
- lightdm is displayed rotated with the touchscreen badly oriented
- steam in desktop mode is asking me for a password for network stuff (not sure why 🤔), but I can't type any as my user doesn't have a password
- going back to gaming mode from desktop is easier by rebooting, otherwise if I logout from GNOME, i need to pick the gaming mode in lightdm with its rotated screen/touchscreen and this mean the next time I need to go back in desktop mode, I'll have to pick the session again instead of reusing the last one

It would be so much better if:

- switching to desktop mode was automatic without the display manager screen
- switching to gaming mode was done through a shortcut on desktop mode

I'm not sure how ChimeraOS is doing exactly, the gaming session is run by a systemd user service, but I'm not sure how they stop gnome, maybe it's simply stoppping the display-manager service and running the user service, and vice-versa

IMO it's really the only friction Jovian-NixOS has to be the best platform for the steam deck :+1:

**Comment by samueldr** [comment]
We've had a few discussions in the matrix room about that, and the basic answer at the moment is all solutions seem to have problems.

What this means is feel free to think of alternative solutions! Including proposing changes here.

Hint:

 - https://github.com/Jovian-Experiments/Jovian-NixOS/blob/0586e3d1f3689ccd4c8820d2fd7775b39eb14c0d/pkgs/steam-jupiter/fhsenv.nix#L51-L71

**Comment by rapenne-s** [comment]
I don't know if it would appear to be clean, but when I was using a regular linux system on it, I implemented the switch in a brutal way:

The default was to not have display-manager running, but directly boot into gamescope. The script would toggle between gamescope and display-manager by simply killing gamescope and running display-manager, or stopping display-manager and starting gamescope.

With display-manager set to automatic login, it was very fast to switch from one to the other!

As I wasn't able to figure how the "switch to desktop mode" worked on the gamepadUI, I made a .desktop file and added it to steam 😅 but it worked very well.

**Comment by notgne2** [comment]
While searching GitHub to see if anybody else addressed this I came across a great solution from @m1cr0man that seems to work really well with the native switching button.

https://github.com/m1cr0man/nix-configs/blob/main/hosts/deic/modules/gamescope-switcher.nix

**Comment by samueldr** [comment]
Oh, I didn't say how I'm handling the situation: I'm using [specialisations](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=specialisation) in the NixOS config, and reboot into a specialisation with the steam session disabled, and my usual mobile config enabled. It's a bit cumbersome.

I also have added kludges to run a terminal in the steam session, and another kludge to run a video player, both those kludges fulfill like 90% of the needs I would have for getting out of steam anyway.

**Comment by rapenne-s** [comment]
Oh, I didn't think about specialisations for this use case, that does the job beautifully

**Comment by samueldr** [comment]
Fixed with

  - https://github.com/Jovian-Experiments/Jovian-NixOS/pull/84
