### ISSUE TITLE
Blank screen when autologging in with steam-wayland as the default session

### ISSUE THREAD

**Issue by ghost** [Jovian-Experiments/Jovian-NixOS#85]
Tried automatically logging into steam-wayland after boot using the following values below. On the first occasion I tried it I was dropped into a TTY where I could log in. The second and most recent was earlier today when a TTY blinking prompt appeared for a few moments before dropping me into a completely blank screen where I was unable to switch to another TTY. Not from my bluetooth keyboard at least.

```
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "eolas";
  services.xserver.displayManager.defaultSession = "steam-wayland";
```

**Comment by deftdawg** [comment]
I also have had this issue for a very long time, today I developed a workaround for it in my `/etc/nixos/configuration.nix` that basically uses systemd to bounce the `display-manager` service if no `steam` or window manager (`kwin` or `mutter`) or a process with the word `greeter` [present in `sddm` command line when login screen is up] are detected...  I run KDE so I don't know if this will work with `gdm` or whatever login manager `Gnome` uses.

The workaround will run 30s after boot, and run each minute after that, here's the relevant bits:
```nix
  systemd.timers."workaround-steam-start-failure" = {
    wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "30";
        OnUnitActiveSec = "1m";
        Unit = "workaround-steam-start-failure.service";
      };
  };

  systemd.services."workaround-steam-start-failure" = {
    script = ''
      ${pkgs.procps}/bin/ps -ef | ${pkgs.gnugrep}/bin/grep -v grep | ${pkgs.gnugrep}/bin/grep -qE "kwin|mutter|greeter|/steam" && exit
      ${pkgs.coreutils}/bin/echo "Check could not find: Steam/KWin/Mutter or a login greeter screen... "
      # Did we shutdown X and go to text mode? If not, we've got a problem and we need to stop display manager and restart it
      ${pkgs.procps}/bin/ps -ef | ${pkgs.gnugrep}/bin/grep -v grep | ${pkgs.gnugrep}/bin/grep -q xorg-server && (
        ${pkgs.systemd}/bin/systemctl stop display-manager
        sleep 5
        ${pkgs.systemd}/bin/systemctl start display-manager	
      ) || ${pkgs.coreutils}/bin/echo "We are in text mode, no action taken."
    '';
    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  # Enable Steam Big picture w/ MangoHud
  services.xserver.displayManager.defaultSession = "steam-wayland";
  jovian.steam.enable = true;

  # Enable automatic login for the user.
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "deftdawg"; # change to your username
```

**Comment by ghost** [comment]
Cheers for the reply, I'll to trying it out later today.

**Comment by samueldr** [comment]
@alban-eolas Can you try with the now merged newer semantics around session switching?

 - https://github.com/Jovian-Experiments/Jovian-NixOS/pull/84

**Comment by samueldr** [comment]
Stated as fixed in the matrix room.

Anyone with a similar-looking issue, please open a new issue!
