### ISSUE TITLE
Controller firmware updates

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#9]
TODO

 - Package the updater script and firmware binaries

**Comment by zhaofengli** [comment]
The relevant bits are in the `jupiter-hw-support` package in SteamOS which I have packaged [here](https://github.com/zhaofengli/Jovian-NixOS/blob/zhaofeng/pkgs/jupiter-hw-support/default.nix). I should probably split it in multiple outputs.

**Comment by zhaofengli** [comment]
This was fixed in #17 (see `README.md` for instructions).
