### ISSUE TITLE
Drop color management hack

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#91]
Whenever vendor releases stable Steam OS 3.5 with color management stuff, remove the `colorManagementHack` from `modules/steam.nix`.

 - https://github.com/Jovian-Experiments/Jovian-NixOS/pull/83/commits/73c4e25ced14d11eed7e2196b34acff936ae3692

It was made necessary in #83 to not strand users who don't reboot with system updates.

**Comment by pongo1231** [comment]
Any plans on getting rid of it now? This is breaking color management for me on the newer 6.1.*-valve kernels and by now it's probably fair to assume people rebooted already.

**Comment by samueldr** [comment]
OH, THIS IS <del>(probably)</del> verifiably WHY...
