### ISSUE TITLE
Supporting only Pipewire to reduce support load?

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#93]
> [...] I'm thinking about adding an assertion/warning so we only support Pipewire in the repo.

_Originally posted by @zhaofengli in https://github.com/Jovian-Experiments/Jovian-NixOS/pull/92#pullrequestreview-1463392221_

I guess a warning is less troublesome than an assert.

**Comment by K900** [comment]
https://github.com/Jovian-Experiments/Jovian-NixOS/commit/6005e8391e1ff704fceeee4f7cc9cbb61769a52d
