### ISSUE TITLE
[~2023-06-07] Steam (beta) fails to launch

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#94]
Tracking issue.

Unclear if it is specific to our configuration, but I suspect not given (assumedly) stock NixOS users are hitting a similar issue.

 - ref: https://github.com/ValveSoftware/steam-for-linux/issues/9321#issuecomment-1581566134

It may be wise to open a NixOS issue once there's enough clues to say it's not a Jovian-NixOS-only thing.

* * *

cc @n3oney who authored that comment  
cc @azahi @ghishadow and @MordragT who reacted on that issue comment (assuming NixOS users)

Sorry to directly ping all of you, but if you can confirm that you are on NixOS "proper", and the "channel" in use for Steam, that would help, at least we could open a tracking issue there too.

* * *

### What's happening?

Launching Steam (channel = steam deck; beta) currently fails.

The updater "applet" launches, downloaded (initially) the update, verifies, then (peeking at journalctl) launches steam.

Then *steam itself* crashes:

```
src/steamUI/steamuisharedjscontroller.cpp (449) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (449) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (449) : Fatal assert; application exiting
src/steamUI/steamuisharedjscontroller.cpp (449) : Fatal assert; application exiting
```

These are the last messages before the breakpad exception handler picks up.

##### Version

```
~ $ journalctl --output=cat --boot | grep 'installed version' | tail -n1
[2023-06-07 20:28:23] Download skipped: /steam_client_steamdeck_publicbeta_ubuntu12 version 1686092969, installed version 1686092969, existing pending version 0
```

Version `1686092969` AFAICT here. (Assuming a date, from June 6th.)

**Comment by MordragT** [comment]
Hi yeah I am running on the unstable branch of "proper" nixos.

**Comment by samueldr** [comment]
Known workaround, will require a NixOS-side change to fix here.

 - https://github.com/NixOS/nixpkgs/issues/236561#issuecomment-1581879353

**Comment by azahi** [comment]
Fix from https://github.com/NixOS/nixpkgs/pull/236606 worked for me. Shall we close this issue since it's already merged?

EDIT: Just realised that this is not the Nixpkgs repo xD

**Comment by samueldr** [comment]
Our tracking issue will stay opened/pinned until the fix propagates to the channel, and then maybe a few days more since it'll be forgotten about ;)

 - https://nixpk.gs/pr-tracker.html?pr=236606

**Comment by ashkitten** [comment]
"a few days" later: 🤣

**Comment by zhaofengli** [comment]
It's indeed been open for too long 😆 Let's close assuming most have already upgraded.
