### ISSUE TITLE
Gnome and Jovian conflict on pulseaudio

### ISSUE THREAD

**Issue by ElvishJerricco** [Jovian-Experiments/Jovian-NixOS#99]
```
error: The option `hardware.pulseaudio.enable' has conflicting definition values:
       - In `/Jovian-NixOS/modules/steamdeck/sound.nix': false
       - In `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/gnome.nix': true
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
(use '--show-trace' to show detailed location information)
```

It can be fixed with:

```
  hardware.pulseaudio.enable = lib.mkForce false;
  services.pipewire.enable = lib.mkForce true;
```

We should probably include something to this effect in jovian.

**Comment by samueldr** [comment]
One detail: probably we should set it with a priority below `mkForce` (but higher than the unqualified), so that `mkForce` still works for end-users, making the UX for end-users just a tiny bit better.

**Comment by ElvishJerricco** [comment]
@samueldr Yea, or we could just not set `services.pipewire.enable = true` when gnome is enabled. Or do we think Jovian really needs to be using pipewire?

**Comment by samueldr** [comment]
See https://github.com/Jovian-Experiments/Jovian-NixOS/issues/93 ; unsure though.

**Comment by K900** [comment]
https://github.com/Jovian-Experiments/Jovian-NixOS/commit/6005e8391e1ff704fceeee4f7cc9cbb61769a52d
